import React, { useState } from "react";
import Head from "next/head";
import { Navbar, Footer } from "../../../components";
import { useRouter } from "next/router";
import PaymentForm from "@/components/stripe/PaymentForm";
import { withRole } from "../../../utils/withAuthorization";

function CreditCardInfo() {
  const navigation = useRouter();

  return (
    <>
      <Head>
        <title>Credit Card Information</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" d-flex flex-column justify-content-between  min-vh-100">
        <Navbar />
        <div className="m-auto" style={{ maxWidth: "600px", width: "100%" }}>
          <div>
            <PaymentForm title="Credit card information" />
            {/* <div className="form-check">
                  <input
                    className="form-check-input"
                    type="checkbox"
                    value=""
                    id="flexCheckDefault"
                  />
                  <label className="form-check-label" for="flexCheckDefault">
                    Save the payment information for future use
                  </label>
                </div> */}
            <div className="d-flex gap-2 justify-content-center mt-3">
              <button
                className="w-25 btn_primary text-light p-2 rounded fw-bold "
                onClick={() => navigation.push("/")}
              >
                Save
              </button>
            </div>
          </div>
        </div>

        <Footer />
      </main>
    </>
  );
}

export default withRole(CreditCardInfo, ["Student"]);
