

import React, { useState } from "react";
import Head from "next/head";
import { ParentNavbar, Footer } from "../../../components";
import Calendar from "react-calendar";
import {useRouter} from "next/router"
import { withRole } from '../../../utils/withAuthorization';

function ParentRequestInterview() {
  const navigation = useRouter();
  const [value, onChange] = useState(new Date());
 
  const onContinue = () => {
    navigation.push("/parent/scheduleclass")
  }
  return (
    <>
      <Head>
        <title>Request Interview</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ParentNavbar isLogin={true} />
      <main className="container-fluid">
      <div
          className="row"
          style={{ minHeight: "90vh" }}
        >
          <div className="col-12 col-lg-6 pt-5">
          <p className="fw-bold text-center">
              Schedule Interview with John Doe
            </p>
            <Calendar onChange={onChange} value={value} />
          </div>
          <div className="col-12 col-lg-6 pt-5">
          <p className="fw-bold text-center text-white">I</p>
            <div className="shadow rounded py-5">
              <div
                className="d-flex justify-content-between gap-4 px-3"
                style={{ minHeight: "400px" }}
              >
                <div className="w-100 ">
                  <p className="p-0 m-0 fw-bold pb-2">Select time</p>
                  <div className="border rounded p-2 px-3">
                    <p className="p-0 m-0 py-1 fw-bold">7:00 am</p>
                    <p className="p-0 m-0 py-1 fw-bold">7:15 am</p>
                    <p className="p-0 m-0 py-1 fw-bold">7:30 am</p>
                    <br />
                    <br />
                    <br />
                    <br />
                    <br />
                    <br />
                    <br />
                    <br />
                    <br />
                    <p className="p-0 m-0 py-1 fw-bold">4:45 pm</p>
                    <p className="p-0 m-0 py-1 fw-bold">5:00 pm</p>
                  </div>
                </div>
                <div className=" w-100">
            

<p className="p-0 m-0 fw-bold text-center py-2">
                    Your dependent's information
                  </p>

                  <div className="d-flex align-items-center gap-3 py-3">
                    <h6 className="text-dark fw-bold p-0 m-0 flex-fill">
                      On behalf of:
                    </h6>

                    <select className="w-25 p-2 flex-fill rounded outline-0 border border_gray ">
                      <option>Select</option>
                      <option>Option 1</option>
                      <option>Option 2</option>
                    </select>
                  </div>

                  <div className="d-flex align-items-center gap-3 py-3">
                    <h6 className="text-dark fw-bold p-0 m-0 flex-fill">
                      Course:
                    </h6>

                    <select className="w-25 flex-fill p-2 rounded outline-0 border border_gray ">
                      <option>Select</option>
                      <option>Option 1</option>
                      <option>Option 2</option>
                    </select>
                  </div>

                  <div className="d-flex align-items-center gap-3 py-3">
                    <h6 className="text-dark fw-bold p-0 m-0 flex-fill">
                      Mode:
                    </h6>

                    <select className="w-25 flex-fill p-2 rounded outline-0 border border_gray ">
                      <option>Select</option>
                      <option>Option 1</option>
                      <option>Option 2</option>
                    </select>
                  </div>

                  <h6 className="text-dark fw-bold">Mode:</h6>

                  <p className="text-dark fw-bold py-2">Intermediate</p>

                  <h6 className="text-dark fw-bold">Grade:</h6>

                  <p className="text-dark fw-bold py-2">Middle School</p>
               
                </div>
              </div>
              <div className="d-flex gap-2 justify-content-center pt-5">
                <button className="w-25 btn_primary text-light p-2 rounded fw-bold " onClick={()=>onContinue()}>
                  Schedule
                </button>
              </div>
            </div>
          </div>
          </div>


     
      </main>
      <Footer />
    </>
  );
}


export default withRole(ParentRequestInterview, ['Parent']);
