import React, { useState } from "react";
import Head from "next/head";
import { Navbar, Footer } from "./../../../components";
import { BsCheck2Circle } from "react-icons/bs";
import { MdEmail, MdArrowForwardIos } from "react-icons/md";
import { MultiSelect } from "react-multi-select-component";
export default function StudentRegistrationCCPay() {
  const options = [
    { label: "Grapes ", value: "grapes" },
    { label: "Mango ", value: "mango" },
    { label: "Strawberry ", value: "strawberry" },
    { label: "Watermelon ", value: "watermelon" },
    { label: "Pear ", value: "pear", disabled: true },
    { label: "Apple ", value: "apple" },
    { label: "Tangerine ", value: "tangerine" },
    { label: "Pineapple ", value: "pineapple" },
    { label: "Peach ", value: "peach" },
  ];

  const [selected, setSelected] = useState([]);

  return (
    <>
      <Head>
        <title>Profile Edit Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar isLogin={true} />
      <main className="container-fluid">
        <div
          className="p-5 "
          style={{ minHeight: "90vh", maxWidth: "1700px", margin: "auto" }}
        >
          <div class="row">
            <div class="col-12 col-lg-4">
              <div className="shadow rounded-10 bg-white py-4">
                <div className="px-4">
                  <h5 className="fw-bold py-3">John Lark</h5>

                  <p className="w-75 bg_secondary text-white p-2 rounded d-flex align-items-center gap-2 fw-bold">
                    <MdEmail style={{ fontSize: "22px" }} />
                    student@123.com
                  </p>

                  <p className="p-0 m-0 py-2 fw-bold">Parent1/guardian1</p>

                  <input
                    type="text"
                    className="w-100 p-2 rounded outline-0 border border_gray text_gray  mb-3"
                    placeholder="Parent1/guardian1"
                  />
                  <p className="p-0 m-0 py-2 fw-bold">Parent2/guardian2</p>
                  <input
                    type="text"
                    className="w-100 p-2 rounded outline-0 border border_gray text_gray  mb-3"
                    placeholder="Parent2/guardian2"
                  />
                  <hr className="bg_secondary" />

                  <div></div>

                  <div className="d-flex gap-2 justify-content-center py-3">
                    <button className="px-4 btn btn-success text-light p-2 rounded fw-bold d-flex align-items-center justify-content-center gap-2">
                      <BsCheck2Circle className="h3 m-0 p-0" /> Save Profile
                    </button>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-12 col-lg-8 py-2">
              <div className="shadow rounded-10 p-5 bg-white">
                <div className="row">
                  <div className="col-12 col-md-4">
                    <h4 className="fw-bold">Grade:</h4>

                    <div class="form-check">
                      <input
                        class="form-check-input"
                        type="radio"
                        value=""
                        id="flexCheckDefault"
                        name="grades"
                      />
                      <label class="form-check-label" for="flexCheckDefault">
                        Elementry &#40;&#60;10yrs&#41;
                      </label>
                    </div>
                    <div class="form-check">
                      <input
                        class="form-check-input"
                        type="radio"
                        value=""
                        id="flexCheckDefault"
                        name="grades"
                      />
                      <label class="form-check-label" for="flexCheckDefault">
                        Middle School &#40;&#60;11yrs - 13yrs&#41;
                      </label>
                    </div>
                    <div class="form-check">
                      <input
                        class="form-check-input"
                        type="radio"
                        value=""
                        id="flexCheckDefault"
                        name="grades"
                      />
                      <label class="form-check-label" for="flexCheckDefault">
                        High School &#40;&#60;14yrs - 18yrs&#41;
                      </label>
                    </div>
                    <div class="form-check">
                      <input
                        class="form-check-input"
                        type="radio"
                        value=""
                        id="flexCheckChecked"
                        name="grades"
                      />
                      <label class="form-check-label" for="flexCheckChecked">
                        College & Beyond &#40;&gt;18yrs&#41;
                      </label>
                    </div>
                  </div>
                  <div className="col-12 col-md-4 border-start px-4 border_primary">
                    <h4 className="fw-bold">Delivery Mode:</h4>
                    <div class="form-check">
                      <input
                        class="form-check-input"
                        type="checkbox"
                        value=""
                        id="flexCheckDefault"
                      />
                      <label class="form-check-label" for="flexCheckDefault">
                        In person
                      </label>
                    </div>{" "}
                    <div class="form-check">
                      <input
                        class="form-check-input"
                        type="checkbox"
                        value=""
                        id="flexCheckDefault"
                      />
                      <label class="form-check-label" for="flexCheckDefault">
                        Online
                      </label>
                    </div>
                  </div>
                  <div className="col-12 col-md-4 border-start px-4 border_primary">
                    <h4 className="fw-bold">Language Preference:</h4>
                    <select className="w-100 p-2 rounded outline-0 border border_gray text_gray ">
                      <option>Select</option>
                      <option>Select</option>
                      <option>Select</option>
                    </select>
                  </div>
                </div>
              </div>

              <div className="shadow rounded-10 pt-2 pb-5 bg-white  my-4">
                <div className="p-4 w-50 m-auto">
                  <h4 className="fw-bold m-0 p-0 pb-3 text-center">
                    Course List:
                  </h4>

                  <MultiSelect
                    options={options}
                    value={selected}
                    onChange={setSelected}
                    labelledBy={"Select Course"}
                    isCreatable={true}
                  />
                </div>

                <div className="row m-0 p-0 ">
                  <div className="col ">
                    <h4 className="fw-bold m-0 p-0">Courses:</h4>
                  </div>
                  <div className="col ">
                    <h4 className="fw-bold m-0 p-0">Perference:</h4>
                  </div>

                  <div className="row m-0 p-0 py-2 pt-4">
                    <div className="col d-flex align-items-center gap-2">
                      <MdArrowForwardIos className="text_primary h4 p-0 m-0" />
                      <p className="fw-bold m-0 p-0 h5 fw-lighter">Course 1</p>
                    </div>
                    <div className="col ">
                      <select className="w-100 p-2 rounded outline-0 border border_gray text_gray ">
                        <option>Beginner</option>
                        <option>Intermediate</option>
                        <option>Semi-Expert</option>
                      </select>
                    </div>
                  </div>

                  <div className="row m-0 p-0 py-2">
                    <div className="col d-flex align-items-center gap-2">
                      <MdArrowForwardIos className="text_primary h4 p-0 m-0" />
                      <p className="fw-bold m-0 p-0 h5 fw-lighter">Course 2</p>
                    </div>
                    <div className="col ">
                      <select className="w-100 p-2 rounded outline-0 border border_gray text_gray ">
                        <option>Beginner</option>
                        <option>Intermediate</option>
                        <option>Semi-Expert</option>
                      </select>
                    </div>
                  </div>

                  <div className="row m-0 p-0 py-2">
                    <div className="col d-flex align-items-center gap-2">
                      <MdArrowForwardIos className="text_primary h4 p-0 m-0" />
                      <p className="fw-bold m-0 p-0 h5 fw-lighter">Course 3</p>
                    </div>
                    <div className="col ">
                      <select className="w-100 p-2 rounded outline-0 border border_gray text_gray ">
                        <option>Beginner</option>
                        <option>Intermediate</option>
                        <option>Semi-Expert</option>
                      </select>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>

      <Footer />
    </>
  );
}
