import styles from "@/styles/Navbar.module.css";
import { useState } from "react";
import { useRouter } from "next/router";
import { Navbar, Footer } from "./../../components";
import Head from "next/head";

export default function ChangePassword() {
  const [showActivation, setShowActivation] = useState(false);
  const navigation = useRouter();
  const onContinue = () => {
    if (showActivation) {
      return navigation.push("signin");
    }
    setShowActivation(true);
  };
  return (
    <>
      <Head>
        <title>Report</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar isLogin={true} />
      <main className="container-fluid">
        <div
          className={` container-sm w-50 pt-5`}
          style={{ minHeight: "90vh" }}
        >
          <div className="container w-75">
            <input
              className="form-control my-3"
              type="password"
              placeholder="Old password"
            />
            <input
              className="form-control my-3"
              type="password"
              placeholder="New password"
            />
            <input
              className="form-control my-3"
              type="password"
              placeholder="Confirm new password"
            />
            {showActivation ? (
              <input
                className="form-control my-3"
                type="text"
                placeholder="Verification code"
              />
            ) : null}

            <div className="text-end">
              <button
                onClick={onContinue}
                className={`${styles.btn_primary} py-2 px-4 fw-bold text-white rounded text-end`}
                type="submit"
              >
                Continue
              </button>
            </div>
            <div>
              {showActivation ? (
                <p>Great!!! password updated successfully</p>
              ) : null}
            </div>
          </div>
        </div>
      </main>
      <Footer />
    </>
  );
}
