import React from "react";
import Head from "next/head";
import { Navbar, Footer } from "./../../components";

export default function RegistrationGrade() {
  return (
    <>
      <Head>
        <title>Sign In Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container-fluid">
        <Navbar />
        <div className="py-5 ">
          <h5 className="text-secondary fw-bold text-center py-4">
            Tell us about yourself?
          </h5>

          <div
            className=" d-flex flex-wrap justify-content-center m-auto gap-4 py-5"
            style={{ maxWidth: "700px" }}
          >
            <div
              style={{
                backgroundImage: 'url("/assets/5_plus.png")',
                backgroundRepeat: "no-repeat",
                backgroundSize: "100% 100%",
                width: "240px",
                height: "240px",
                position: "relative",
                borderRadius: "10px",
              }}
            >
              <input
                className="form-check-input position-absolute"
                style={{ top: "5px", right: "5px" }}
                type="radio"
                name="flexRadioDefault"
                id="flexRadioDefault1"
              />
              <div className="position-absolute bottom-0 p-2 bg-light w-100 bg-opacity-50 fw-bold">
                <small className="text-secondary">
                  Elementry &#40;&#60;10yrs&#41;
                </small>
              </div>
            </div>
            <div
              style={{
                backgroundImage: 'url("/assets/10_plus.png")',
                backgroundRepeat: "no-repeat",
                backgroundSize: "100% 100%",
                width: "240px",
                height: "240px",
                position: "relative",
                borderRadius: "10px",
              }}
            >
              <input
                className="form-check-input position-absolute"
                style={{ top: "5px", right: "5px" }}
                type="radio"
                name="flexRadioDefault"
                id="flexRadioDefault1"
              />

              <div className="position-absolute bottom-0 p-2 bg-light w-100 bg-opacity-50 fw-bold">
                <small className="text-secondary">
                  Middle School &#40;&#60;11yrs - 13yrs&#41;
                </small>
              </div>
            </div>

            <div
              style={{
                backgroundImage: 'url("/assets/14_plus.png")',
                backgroundRepeat: "no-repeat",
                backgroundSize: "100% 100%",
                width: "240px",
                height: "240px",
                position: "relative",
                borderRadius: "10px",
              }}
            >
              <input
                className="form-check-input position-absolute"
                style={{ top: "5px", right: "5px" }}
                type="radio"
                name="flexRadioDefault"
                id="flexRadioDefault1"
              />

              <div className="position-absolute bottom-0 p-2 bg-light w-100 bg-opacity-50 fw-bold">
                <small className="text-secondary">
                  High School &#40;&#60;14yrs - 18yrs&#41;
                </small>
              </div>
            </div>

            <div
              style={{
                backgroundImage: 'url("/assets/18_plus.png")',
                backgroundRepeat: "no-repeat",
                backgroundSize: "100% 100%",
                width: "240px",
                height: "240px",
                position: "relative",
                borderRadius: "10px",
              }}
            >
              <input
                className="form-check-input position-absolute"
                style={{ top: "5px", right: "5px" }}
                type="radio"
                name="flexRadioDefault"
                id="flexRadioDefault1"
              />

              <div className="position-absolute bottom-0 p-2 bg-light w-100 bg-opacity-50 fw-bold">
                <small className="text-secondary">
                  College & Beyond &#40;&gt;18yrs&#41;
                </small>
              </div>
            </div>
          </div>
          <div className="d-flex gap-2 justify-content-center mt-3">
            <button className="btn_primary text-light p-2 px-5 rounded fw-bold ">
              Continue
            </button>
          </div>
        </div>
        <Footer />
      </main>
    </>
  );
}
