version: 0.2
phases:
  install:
    commands:
      - echo "Installing Node.js 18"
      - n 18
      - npm install next
      - npm install typescript
  pre_build:
    commands:
      - uname -m      
  build:
    commands:
      - echo "Starting the build process"
      - npm install
      - npm run build
artifacts:
  files:
    - '**/*'