import React, { useState } from "react";
import Head from "next/head";
import { Inter } from "next/font/google";
import { TutorNavbar, Footer } from "../../../components";
import { FiRefreshCw } from "react-icons/fi";
import { TbSpeakerphone } from "react-icons/tb";
import { useRouter } from "next/router";
import { withRole } from "../../../utils/withAuthorization";
import styles from "../../../styles/Home.module.css";
import FinancialReport from "@/components/financialReport";
function InstructorFinancialReport() {
  const navigation = useRouter();

  const [activeTab, setActiveTab] = useState("schedule");

  const handleTabClick = (tabName) => {
    setActiveTab(tabName);
  };
  return (
    <>
      <Head>
        <title> Instructor Financial Report </title>{" "}
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>{" "}
      <TutorNavbar isLogin={true} />
      <div className="d-flex justify-content-center bg-light p-2">
        <div
          className={`p-2 cursor-pointer h-100 w-25 border-dark${
            activeTab === "option1" && "bg-white"
          }`}
          onClick={() => handleTabClick("revenue")}
        >
          Revenue
        </div>
        <div
          className={`p-2 cursor-pointer  h-100 w-25  ${
            activeTab === "option2" && "bg-white"
          }`}
          onClick={() => handleTabClick("withdrawal")}
        >
          Withdrawal
        </div>
        {/* Add more tab items for additional options */}
      </div>
      {activeTab === "revenue" ? (
        <FinancialReport role="instructor" />
      ) : (
        <main className="container-fluid">
          <div className="container"></div>
        </main>
      )}
      <Footer />
    </>
  );
}

export default withRole(InstructorFinancialReport, ["Instructor"]);
