import Review from "@/components/review/review";
import { ParentNavbar, Footer } from "../../../components";
import Head from "next/head";
import { withRole } from "../../../utils/withAuthorization";

function ParentInstructorReview() {
  return (
    <>
      <Head>
        <title> Parent Review Instructor </title>{" "}
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>{" "}
      <ParentNavbar isLogin={true} /> 
      <Review role="parent" />
      <Footer />
    </>
  );
}

export default withRole(ParentInstructorReview, ["Parent"]);
