import React, { useState } from "react";
import Head from "next/head";
import { Navbar, Footer } from "../../../components";
import Calendar from "react-calendar";
import { BsFillSendFill } from "react-icons/bs";

export default function StudentRegistrationCCPay() {
  const [value, onChange] = useState(new Date());

  return (
    <>
      <Head>
        <title>Student Schedule Class</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container-fluid">
        <Navbar isLogin={true} />
        <div
          className="d-flex justify-content-between gap-5  p-5 "
          style={{ height: "90vh" }}
        >
          <div className="w-50">
            <p className="fw-bold text-center">Schedule class with John Doe</p>
            <Calendar onChange={onChange} value={value} />
          </div>
          <div className="w-50">
            <p className="fw-bold text-center text-white">I</p>
            <div className="shadow rounded py-5">
              <div
                className="d-flex justify-content-between gap-4 px-5"
                style={{ minHeight: "400px" }}
              >
                <div className="w-100 ">
                  <p className="p-0 m-0 fw-bold pb-2">Select time</p>
                  <div className="border rounded">
                    <p className="p-0 m-0 py-1 fw-bold bg-light p-2  px-3">
                      7:00 am
                    </p>
                    <p className="p-0 m-0 py-1 fw-bold bg-light p-2  px-3">
                      8:00 am
                    </p>
                    <p className="p-0 m-0 py-1 fw-bold p-2  px-3">9:00 am</p>
                    <br />
                    <br />
                    <br />
                    <br />
                    <br />
                    <br />
                    <br />
                    <br />
                    <br />
                    <p className="p-0 m-0 py-1 fw-bold p-2  px-3">4:00 pm</p>
                    <p className="p-0 m-0 py-1 fw-bold p-2  px-3">5:00 pm</p>
                  </div>
                </div>
                <div className=" w-100">
                  <p className="p-0 m-0 fw-bold text-center py-2">
                    Your information
                  </p>
                  <h6 className="text-dark fw-bold">
                    You selected 2 hours slot
                  </h6>

                  <div className="py-1">
                    <div class="form-check">
                      <input
                        class="form-check-input"
                        type="radio"
                        name="flexRadioDefault"
                        id="flexRadioDefault1"
                      />
                      <label class="form-check-label" for="flexRadioDefault1">
                        One-Time
                      </label>
                    </div>
                    <div class="form-check">
                      <input
                        class="form-check-input"
                        type="radio"
                        name="flexRadioDefault"
                        id="flexRadioDefault2"
                      />
                      <label class="form-check-label" for="flexRadioDefault2">
                        Weekly Recurrence
                      </label>
                    </div>
                    <div class="form-check">
                      <input
                        class="form-check-input"
                        type="radio"
                        name="flexRadioDefault"
                        id="flexRadioDefault1"
                      />
                      <label class="form-check-label" for="flexRadioDefault1">
                        Bi-Weekly
                      </label>
                    </div>
                    <div class="form-check">
                      <input
                        class="form-check-input"
                        type="radio"
                        name="flexRadioDefault"
                        id="flexRadioDefault2"
                      />
                      <label class="form-check-label" for="flexRadioDefault2">
                        Monthly
                      </label>
                    </div>
                  </div>

                  <div className="d-flex align-items-center gap-3 py-2">
                    <h6 className="text-dark fw-bold p-0 m-0 flex-fill">
                      On behalf of:
                    </h6>

                    <select className="w-25 p-2 flex-fill rounded outline-0 border border_gray text_gray">
                      <option>Select</option>
                      <option>Option 1</option>
                      <option>Option 2</option>
                    </select>
                  </div>

                  <div className="d-flex align-items-center gap-3 py-2">
                    <h6 className="text-dark fw-bold p-0 m-0 flex-fill">
                      Course:
                    </h6>

                    <select className="w-25 flex-fill p-2 rounded outline-0 border border_gray text_gray">
                      <option>Select</option>
                      <option>Option 1</option>
                      <option>Option 2</option>
                    </select>
                  </div>

                  <div className="d-flex align-items-center gap-3 py-2">
                    <h6 className="text-dark fw-bold p-0 m-0 flex-fill">
                      Mode:
                    </h6>

                    <select className="w-25 flex-fill p-2 rounded outline-0 border border_gray text_gray">
                      <option>Select</option>
                      <option>Option 1</option>
                      <option>Option 2</option>
                    </select>
                  </div>

                  <div className="py-2 d-flex align-items-center gap-4">
                    <h6 className="text-dark fw-bold m-0 p-0">Skills:</h6>

                    <h6 className="text-dark fw-bold m-0 p-0">Intermediate</h6>
                  </div>

                  <div className="py-2 d-flex align-items-start gap-4">
                    <h6 className="text-dark fw-bold m-0 p-0">Grade:</h6>
                    <div>
                      <h6 className="text-dark fw-bold m-0 p-0">
                        Middle School
                      </h6>
                      <h6 className="text-dark fw-bold m-0 p-0">
                        &#40;12yrs - 14yrs&#41;
                      </h6>
                    </div>
                  </div>
                </div>
              </div>
              <div className="d-flex gap-2 justify-content-center pt-5">
                <button className="w-25 btn_primary text-light p-2 rounded fw-bold ">
                  Schedule
                </button>
              </div>
            </div>
          </div>
        </div>

        <Footer />
        {/* Chat View Modal */}
        <div className="d-flex justify-content-center align-items-center">
          <div
            className="modal fade"
            id="exampleModal2"
            tabIndex="-1"
            aria-labelledby="exampleModal2Label"
            aria-hidden="true"
          >
            <div className="modal-dialog modal-dialog-centered modal-lg">
              <div className="modal-content p-2">
                <div className="d-flex justify-content-between">
                  <h5 className="modal-title" id="exampleModal2Label"></h5>
                  <button
                    type="button"
                    className="btn-close"
                    data-bs-dismiss="modal"
                    aria-label="Close"
                  ></button>
                </div>
                <div className="modal-body">
                  <div className=" p-3" style={{ minHeight: "400px" }}>
                    <div className="py-1 text-end">
                      <p className="p-0 m-0 fw-bold">
                        lorem ipsum dolor sit amet, consectetur adipis.
                      </p>
                      <small className="p-0 m-0">John Doe 4/11/23 8:15am</small>
                    </div>

                    <div className="py-1">
                      <p className="p-0 m-0 fw-bold">
                        lorem ipsum dolor sit amet, consectetur adipis.
                      </p>
                      <small className="p-0 m-0">John Doe 4/11/23 8:15am</small>
                    </div>
                  </div>

                  <div className=" d-flex align-items-center px-2 gap-2">
                    <input
                      type="text"
                      placeholde=""
                      className="border  p-2 rounded flex-fill"
                    />{" "}
                    <BsFillSendFill className="h3 p-0 m-0" />
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
