import React from "react";
import Head from "next/head";
import Link from "next/link";
import { Navbar, Footer } from "../../../components";
import { BsCheck2Circle } from "react-icons/bs";

export default function RegisterStudent() {
  return (
    <>
      <Head>
        <title>Sign In Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container-fluid">
        <Navbar isLogin={true} />
        <div className="row">
          <div
            className="col-12 col-lg-5 position-relative"
            style={{
              backgroundImage: 'url("/assets/register_group.png")',
              height: "100vh",
              backgroundRepeat: "no-repeat",
              backgroundSize: "100% 100%",
            }}
          ></div>
          <div className="col-12 col-lg-7 d-flex justify-content-center align-items-center ">
            <div className="w-75 p-5">
              <div>
                <div className="d-flex justify-content-between align-items-center mb-3">
                  <h4 className="text-secondary fw-bold">Email:</h4>
                  <p className="bg_secondary text-white p-2 rounded d-flex align-items-center gap-2 fw-bold">
                    <BsCheck2Circle style={{ fontSize: "22px" }} />
                    parent@123.com
                  </p>
                </div>
                <div>
                  <input
                    type="text"
                    className="w-100 p-2 rounded outline-0 border border_gray text_gray  mb-3"
                    placeholder="First Name"
                  />
                  <input
                    type="text"
                    className="w-100 p-2 rounded outline-0 border border_gray text_gray mb-3"
                    placeholder="Last Name"
                  />

                  <input
                    type="text"
                    className="w-100 p-2 rounded outline-0 border border_gray text_gray  mb-3"
                    placeholder="Address 1"
                  />
                  <input
                    type="text"
                    name="addres2"
                    className="w-100 p-2 rounded outline-0 border border_gray text_gray mb-2"
                    placeholder="Address 2"
                  />

                  <div className="d-flex gap-2 my-2">
                    <select className="w-100 p-2 rounded outline-0 border border_gray text_gray mb-3 ">
                      <option>Country</option>
                      <option>Student</option>
                      <option>Student</option>
                    </select>

                    <select className="w-100 p-2 rounded outline-0 border border_gray text_gray mb-3 ">
                      <option>State/Province/Region</option>
                      <option>Student</option>
                      <option>Student</option>
                    </select>
                  </div>
                  <div className="d-flex gap-2 my-2">
                    <select className="w-100 p-2 rounded outline-0 border border_gray text_gray mb-3 ">
                      <option>City</option>
                      <option>Student</option>
                      <option>Student</option>
                    </select>

                    <input
                      type="text"
                      className="w-100 p-2 rounded outline-0 border border_gray text_gray  mb-3"
                      placeholder="Zip/Post Code"
                    />
                  </div>

                  <div className="d-flex gap-2">
                    <input
                      type="password"
                      className="w-100 p-2 rounded outline-0 border border_gray text_gray  mb-3"
                      placeholder="Password"
                    />
                    <input
                      type="password"
                      className="w-100 p-2 rounded outline-0 border border_gray text_gray  mb-3"
                      placeholder="Confirm Password"
                    />
                  </div>

                  <div class="form-check">
                    <input
                      class="form-check-input"
                      type="checkbox"
                      value=""
                      id="flexCheckDefault"
                    />
                    <label class="form-check-label" for="flexCheckDefault">
                      I agree to the Terms of Use and Privacy Policy of GKC
                    </label>
                  </div>
                  <div className="d-flex gap-2 justify-content-between mt-3">
                    <button className="w-25 btn_primary text-light p-2 rounded fw-bold ">
                      Continue
                    </button>
                    <Link
                      href="/"
                      className="text-decoration-none d-flex gap-2 justify-content-center"
                    >
                      <p className="text-secondary fw-bold">
                        Already have an Account?
                      </p>
                      <p className="fw-bold text_secondary">login</p>
                    </Link>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <Footer />
      </main>
    </>
  );
}
