import ContactUs from '@/components/contactUs';
import Head from 'next/head';
import { withRole } from '../../../utils/withAuthorization';

function InstructorContactUs() {
  return (
    <>
      <Head>
        <title> Contact us </title>{' '}
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ContactUs />
    </>
  );
}

export default withRole(InstructorContactUs, ['Instructor']);
