import React, { useState, useEffect } from "react";
import Head from "next/head";
import { Inter } from "next/font/google";
import { Navbar, Footer } from "../../../components";
import {ParentNavbar} from '../../../components/'
import { FiRefreshCw } from "react-icons/fi";
import { TbSpeakerphone } from "react-icons/tb";
import FinancialReport from "@/components/financialReport";
import { useRouter } from "next/router";
import { withRole } from "../../../utils/withAuthorization";
import styles from "../../../styles/Home.module.css";

function ParentFinancialReport() {
  //protection starts
  const nav = useRouter()
  // checking if user logged in starts
  if(typeof window !== 'undefined'){ // here we check if global object successfully loaded
    console.log('lol')
    useEffect(()=>{

      if(JSON.parse(window.localStorage.getItem('gkcAuth')).role === undefined) { //here we check if user signed in
        nav.push('/') 
      } else{
        if(JSON.parse(window.localStorage.getItem('gkcAuth')).role !== 'Parent') { //here we check if user has role Parent
          nav.push('/')
        }
      }

    },[])
  }
  // checking if user logged in ends

  //protection ends

  const navigation = useRouter();
  const onRequestRefund = () => {
    navigation.push("/parent/requestrefund");
  };
  return (
    <>
      <Head>
        <title> Parent Financial Report </title>{" "}
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ParentNavbar isLogin={true} />
      <FinancialReport role="parent" />
      <Footer />
    </>
  );
}

export default withRole(ParentFinancialReport, ["Parent"]);
