// import ContactUs from '@/components/contactUs';
// import Head from 'next/head';
// import { withRole } from '../../../utils/withAuthorization';
// import { TutorNavbar } from './../../../components';

// function InstructorContactUs() {
//   return (
//     <>
//       <Head>
//         <title> Contact us </title>{' '}
//         <meta name="description" content="Generated by create next app" />
//         <meta name="viewport" content="width=device-width, initial-scale=1" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//       <TutorNavbar isLogin={true} />
//       <ContactUs />
//     </>
//   );
// }

// export default withRole(InstructorContactUs, ['Instructor']);

import React, { useState } from 'react';
import Head from 'next/head';
import { TutorNavbar, Footer } from '../../../components';
import { useRouter } from 'next/router';
import { withRole } from '../../../utils/withAuthorization';
import Link from 'next/link';

function BankInfo() {
  const navigation = useRouter();
  const [showPayoneerInput, setShowPayoneerInput] = useState(false);
  const [showPayPalInput, setShowPayPalInput] = useState(false);
  const [popupVisible, setPopupVisible] = useState(false);

  const handleUpdateClick = () => {
    setPopupVisible(true);
    setTimeout(() => {
      setPopupVisible(false);
    }, 3000);
  };

  return (
    <>
      <Head>
        <title> Instructor CC Info </title>{' '}
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>{' '}
      <TutorNavbar isLogin={true} />{' '}
      <div className="w-100">
        <h4
          style={{ marginTop: '120px' }}
          className="text-dark fw-bold pb-2 text-center"
        >
          Tell us where to deposit your payments
        </h4>
        <div className="d-flex mt-5 justify-content-center align-items-center flex-column">
          <div className="d-flex align-items-center gap-5 justify-content-center">
            <p style={{ width: '100px' }} className="fw-bold">
              Payoneer
            </p>
            <button
              onClick={() => setShowPayoneerInput(!showPayoneerInput)}
              style={{ backgroundColor: '#f48342' }}
              className="py-2 px-4 fw-bold text-white rounded"
            >
              Setup
            </button>
          </div>
          {showPayoneerInput && (
            <input
              placeholder="Enter Payoneer info"
              className="mt-3 fw-bold border-2 border-dark p-1"
            ></input>
          )}
          <div className="mt-5 d-flex gap-5 align-items-center justify-content-center">
            <p style={{ width: '100px' }} className="fw-bold">
              PayPal
            </p>
            <button
              onClick={() => setShowPayPalInput(!showPayPalInput)}
              style={{ backgroundColor: '#f48342' }}
              className="py-2 px-4 fw-bold text-white rounded"
            >
              Setup
            </button>
          </div>
          {showPayPalInput && (
            <input
              placeholder="Enter PayPal info"
              className="mt-3 fw-bold border-2 border-dark p-1"
            ></input>
          )}
          <div className="">
            <button
              onClick={handleUpdateClick}
              style={{
                marginTop: '80px',
                width: '500px',
                backgroundColor: '#f48342',
              }}
              className="text-light p-2 w-100 rounded fw-bold  bg-gray-300"
            >
              Update
            </button>
            {popupVisible && (
              <div
                style={{
                  position: 'fixed',
                  top: '50%',
                  left: '50%',
                  transform: 'translate(-50%, -50%)',
                  padding: '55px',
                  backgroundColor: 'white',
                  boxShadow: '0px 0px 10px rgba(0, 0, 0, 0.2)',
                }}
              >
                Your payment info has been updated successfully.
              </div>
            )}
          </div>
        </div>
      </div>
    </>
  );
}

export default withRole(BankInfo, ['Instructor']);
