import React, { useState } from "react";
import Head from "next/head";
import { Navbar, TutorNavbar, Footer } from "./../../../components";
import Calendar from "react-calendar";
import { BsFillChatFill, BsFillSendFill } from "react-icons/bs";
import { GoDeviceCameraVideo } from "react-icons/go";
import { FiEdit } from "react-icons/fi";
import { RiDeleteBin6Line } from "react-icons/ri";
import { withRole } from "../../../utils/withAuthorization";
import { isSameDay, format } from "date-fns";
import axios from "axios";

function EditCalandar() {
  const [value, onChange] = useState(new Date());
  const [selectedDate, setSelectedDate] = useState();

  const handleDateChange = (date) => {
    setSelectedDate(date);
    console.log(selectedDate);
  };

  const getUnavailableDays = async () => {
    const dateToConvert = new Date(selectedDate);
    const convertedDate = format(dateToConvert, "yyyy-MM-dd");
    console.log(convertedDate);

    try {
      var typ = JSON.parse(window.localStorage.getItem("gkcAuth"));
      const res = await axios.post(
        "http://34.227.65.157/instructor/unavailable-day",
        {
          date: convertedDate,
        },
        {
          headers: {
            Authorization: `Bearer ${typ.accessToken}`,
          },
        }
      );
      console.log(res);
      // setProfile(res.data);
      alert("success");
    } catch (error) {
      console.error("Error fetching profile data:", error);
    }
  };
  return (
    <>
      <Head>
        <title> Instructor Landing Page </title>{" "}
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>{" "}
      <TutorNavbar isLogin={true} />{" "}
      <main className="container-fluid">
        <div style={{ height: "90vh" }}>
          <div className="row p-5">
            <div className="col-12 col-lg-6 ">
              <p className="text-center">
                Let us know the days of the week you are available and your
                schedule{" "}
              </p>{" "}
              <table width="100%" role="grid" style={{ tableLayout: "fixed" }}>
                <tbody>
                  <tr>
                    <td roll="gridcell"> Mon </td>{" "}
                    <td roll="gridcell"> Tue </td>{" "}
                    <td roll="gridcell"> Wed </td>{" "}
                    <td roll="gridcell"> Thur </td>{" "}
                    <td roll="gridcell"> Fri </td>{" "}
                    <td roll="gridcell"> Sat </td>{" "}
                    <td roll="gridcell"> Sun </td>{" "}
                  </tr>{" "}
                </tbody>
              </table>
              <div className="row w-75 py-3 ">
                <div className="col-4">
                  <p className="fw-bold"> Available: </p>{" "}
                </div>{" "}
                <div className="col-8">
                  <input
                    className="form-check-input"
                    type="checkbox"
                    id="check1"
                    name="option1"
                    value="something"
                    checked
                  />
                </div>{" "}
              </div>
              <div className="row w-75 py-2 ">
                <div className="col-4">
                  <p className="fw-bold"> Available: </p>{" "}
                </div>{" "}
                <div className="col-8">
                  <div className="row pb-2">
                    <p className="col fw-bold"> From </p>{" "}
                    <select className="w-100 p-2 rounded outline-0 border border_gray   col">
                      <option> 06: 00 am </option> <option> Student </option>{" "}
                      <option> Student </option>{" "}
                    </select>{" "}
                  </div>
                  <div className="row pb-2">
                    <p className="col fw-bold"> To </p>{" "}
                    <select className="w-100 p-2 rounded outline-0 border border_gray  col">
                      <option> 06: 00 pm </option> <option> Student </option>{" "}
                      <option> Student </option>{" "}
                    </select>{" "}
                  </div>{" "}
                </div>{" "}
              </div>{" "}
            </div>{" "}
            <div className="col-12 col-lg-6 ">
              <p className="text-center">
                Select days you don 't intend to tutor e.g. Thanksgaving, etc.{" "}
                <br />
                (Selected days will be blocked on your calandar){" "}
              </p>{" "}
              <Calendar
                onChange={handleDateChange}
                value={selectedDate}
                calendarType="US"
              />{" "}
              {/* <p>{selectedDate.toDateString()}</p> */}{" "}
            </div>{" "}
          </div>{" "}
          <div className=" mt-3 d-flex justify-content-center flex-column align-items-center gap-2">
            <button
              className={`w-25 text-light p-2 rounded fw-bold  bg-gray-300 ${
                selectedDate ? "btn_primary" : "btn_disabled "
              }`}
              disabled={!selectedDate}
              onClick={() => getUnavailableDays()}
            >
              Save{" "}
            </button>{" "}
          </div>{" "}
        </div>{" "}
      </main>{" "}
      <Footer />
    </>
  );
}

export default withRole(EditCalandar, ["Instructor"]);
