import React, { useState } from "react";
import Head from "next/head";
import { Navbar, Footer } from "./../../../components";
import Calendar from "react-calendar";
import { BsFillChatFill, BsFillSendFill } from "react-icons/bs";
import { GoDeviceCameraVideo } from "react-icons/go";
import { FiEdit } from "react-icons/fi";
import { RiDeleteBin6Line } from "react-icons/ri";
export default function StudentRegistrationCCPay() {
  const [value, onChange] = useState(new Date());

  return (
    <>
      <Head>
        <title>Instructor Landing Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar isLogin={true} />
      <main className="container-fluid">
        <div
          className="d-flex justify-content-between gap-5  p-5 "
          style={{ height: "90vh" }}
        >
        
          <div className="w-50">
            <h3 className="text-center">Schedule</h3>
            <div
              className=" shadow p-5 bg-white rounded "
              style={{ minHeight: "400px" }}
            >
              <div className="d-flex align-items-center py-3">
                <h5 className="p-0 m-0 flex-fill fw-bold flex-fill">
                  John Doe
                </h5>
                <h5 className="p-0 m-0 flex-fill fw-bold flex-fill">11:00AM</h5>
                <BsFillChatFill className="p-0 m-0 flex-fill h2 flex-fill" />

                <GoDeviceCameraVideo
                  className="p-0 m-0 flex-fill h2 flex-fill"
                  data-bs-toggle="modal"
                  data-bs-target="#exampleModal2"
                />

                <RiDeleteBin6Line className="p-0 m-0 h2 flex-fill" />
              </div>
              <div className="d-flex align-items-center py-3">
                <h5 className="p-0 m-0 flex-fill fw-bold flex-fill">
                  John Doe
                </h5>
                <h5 className="p-0 m-0 flex-fill fw-bold flex-fill">11:00AM</h5>
                <BsFillChatFill className="p-0 m-0 flex-fill h2 flex-fill" />

                <GoDeviceCameraVideo
                  className="p-0 m-0 flex-fill h2 flex-fill"
                  data-bs-toggle="modal"
                  data-bs-target="#exampleModal2"
                />

                <RiDeleteBin6Line className="p-0 m-0 h2 flex-fill" />
              </div>
              <div className="d-flex align-items-center py-3">
                <h5 className="p-0 m-0 flex-fill fw-bold flex-fill">
                  John Doe
                </h5>
                <h5 className="p-0 m-0 flex-fill fw-bold flex-fill">11:00AM</h5>
                <BsFillChatFill className="p-0 m-0 flex-fill h2 flex-fill" />

                <GoDeviceCameraVideo
                  className="p-0 m-0 flex-fill h2 flex-fill"
                  data-bs-toggle="modal"
                  data-bs-target="#exampleModal2"
                />

                <RiDeleteBin6Line className="p-0 m-0 h2 flex-fill" />
              </div>
              <div className="d-flex align-items-center py-3">
                <h5 className="p-0 m-0 flex-fill fw-bold flex-fill">
                  John Doe
                </h5>
                <h5 className="p-0 m-0 flex-fill fw-bold flex-fill">11:00AM</h5>
                <BsFillChatFill className="p-0 m-0 flex-fill h2 flex-fill" />

                <GoDeviceCameraVideo
                  className="p-0 m-0 flex-fill h2 flex-fill"
                  data-bs-toggle="modal"
                  data-bs-target="#exampleModal2"
                />

                <RiDeleteBin6Line className="p-0 m-0 h2 flex-fill" />
              </div>
            </div>
          </div>
          <div className="w-50">
            <p>Select days you don't intend to tutor e.g. Than</p>
            <Calendar onChange={onChange} value={value} />
          </div>
        </div>

        <Footer />
        
      </main>
    </>
  );
}
