import React, { useState, useEffect } from "react";
import Head from "next/head";
import { Navbar, TutorNavbar, Footer } from "../../components";
import Calendar from "react-calendar";
import { BsFillChatFill, BsFillSendFill } from "react-icons/bs";
import { GoDeviceCameraVideo } from "react-icons/go";
import { FiEdit } from "react-icons/fi";
import { RiDeleteBin6Line } from "react-icons/ri";
import { useRouter } from "next/router";
import moment from "moment";
import FirebaseChat from "../../hooks/firebase-chat";
import { withRole } from "./../../utils/withAuthorization";
import axios from "axios";

function InstructorLandingPage() {
  const navigation = useRouter();

  const { sendMessage, messages, setChatInfo, setNewMessage, newMessage } =
    FirebaseChat();
  const [value, onChange] = useState(new Date());
  const onContinue = () => {
    navigation.push("/instructor/video");
  };
  const instructor = {
    name: "Nouman",
    id: 1,
  };
  const student = {
    courseId: 1,
    name: "John",
    id: 2,
    parentId: 4,
  };

  const openChat = (chatId) => {
    setChatInfo({
      sender: {
        ...instructor,
      },
      receiver_user: {
        ...student,
      },
      course_id: chatId,
    });
  };
  const handleTextChange = (e) => {
    setNewMessage(e.target.value);
  };

  const a = async () => {
    const res = await axios.get("http://34.227.65.157/user/logged-user-role", {
      headers: {
        Authorization: `Bearer ${response.data.accessToken}`,
      },
    });
    console.log(res.data);
  };
  return (
    <>
      <Head>
        <title>Instructor Landing Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TutorNavbar isLogin={true} />
      <main className="container-fluid">
        <div
          className="d-flex justify-content-between gap-5  p-5 "
          style={{ height: "90vh" }}
        >
          <div className="w-50">
            <div
              className="d-flex justify-content-end p-2"
              onClick={() => navigation.push("/instructor/editcalandar")}
            >
              <FiEdit style={{ fontSize: "24px" }} />
            </div>
            <Calendar onChange={onChange} value={value} />
          </div>
          <div className="w-50">
            <h3 className="text-center">Schedule</h3>
            <div
              className=" shadow p-5 bg-white rounded "
              style={{ minHeight: "400px" }}
            >
              {[1, 2, 3].map((item) => {
                return (
                  <div
                    onClick={() => openChat(item)}
                    className="d-flex align-items-center py-3"
                  >
                    <h5 className="p-0 m-0 flex-fill fw-bold flex-fill">
                      John Doe
                    </h5>
                    <h5 className="p-0 m-0 flex-fill fw-bold flex-fill">
                      11:00AM
                    </h5>
                    <BsFillChatFill
                      className="p-0 m-0 flex-fill h2 flex-fill"
                      data-bs-toggle="modal"
                      data-bs-target="#exampleModal2"
                    />

                    <GoDeviceCameraVideo
                      className="p-0 m-0 flex-fill h2 flex-fill"
                      onClick={() => onContinue()}
                    />

                    <RiDeleteBin6Line className="p-0 m-0 h2 flex-fill" />
                  </div>
                );
              })}
            </div>
          </div>
        </div>

        <Footer />
        {/* Chat View Modal */}
        <div className="d-flex justify-content-center align-items-center">
          <div
            className="modal fade"
            id="exampleModal2"
            tabIndex="-1"
            aria-labelledby="exampleModal2Label"
            aria-hidden="true"
          >
            <div className="modal-dialog modal-dialog-centered modal-lg">
              <div className="modal-content p-2">
                <div className="d-flex justify-content-between">
                  <h5 className="modal-title" id="exampleModal2Label"></h5>
                  <button
                    type="button"
                    className="btn-close"
                    data-bs-dismiss="modal"
                    aria-label="Close"
                  ></button>
                </div>
                <div className="modal-body">
                  <div className=" p-3" style={{ minHeight: "400px" }}>
                    {messages.map((item, index) => {
                      let date = item.timestamp.seconds * 1000;
                      return (
                        <div
                          key={index}
                          className={`py-1 ${
                            item?.user?.id == instructor?.id ? "text-end" : ""
                          }`}
                        >
                          <p className="p-0 m-0 fw-bold">{item.message}</p>
                          <small className="p-0 m-0">
                            {`${item?.user?.name}  ${moment(date).format(
                              "d/MM/YY"
                            )}`}{" "}
                            {moment(date).format("hh:mm a")}
                          </small>
                        </div>
                      );
                    })}
                  </div>

                  <div className=" d-flex align-items-center px-2 gap-2">
                    <input
                      value={newMessage}
                      onChange={handleTextChange}
                      type="text"
                      placeholde=""
                      className="border  p-2 rounded flex-fill"
                    />{" "}
                    <BsFillSendFill
                      onClick={() => sendMessage({ type: "instructor" })}
                      className="h3 p-0 m-0"
                    />
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}

export default withRole(InstructorLandingPage, ["Instructor"]);
