import React, { useState } from "react";
import Head from "next/head";
import { Inter } from "next/font/google";
import { Navbar, Footer } from "../../components";
import {FiRefreshCw} from "react-icons/fi"
import {TbSpeakerphone} from "react-icons/tb"
export default function StudentFinancialReport() {
  return (
    <>
      <Head>
        <title>Student Financial Report</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Navbar isLogin={true} />
      <main className="container-fluid">
          <div className="container ">
            <div className=" p-5" style={{minHeight:"100vh"}}>
            <h5 className="text-dark fw-bold text-center">
                  Report
                </h5>
 <div  className="border rounded p-4 my-4" style={{minHeight:"500px"}}>

                <div className="d-flex w-50 m-auto justify-content-center gap-4 mb-4" >
               <div className="d-flex align-items-center gap-3">
               <p className="fw-bold m-0 p-0">From</p>
                <input id="startDate" class="form-control" type="date" />
                </div>
<div className="d-flex align-items-center gap-3">
<p className="fw-bold m-0 p-0">To</p>

                <input id="startDate" class="form-control" type="date" />
                <FiRefreshCw style={{fontSize:"35px"}}/>
                </div>
 </div>
 
                <table class="table ">
  <thead>
    <tr className="bg-light">
      <th scope="col">Date</th>
      <th scope="col">Tutor</th>
      <th scope="col">Course</th>
      <th scope="col">Hours Scheduled</th>
      <th scope="col">Course Cost</th>
      <th scope="col">Booking Fee</th>
      <th scope="col">Total Payment</th>
    </tr>
  </thead>
  <tbody>
    <tr>
    <th className="fw-bold" scope="row" >05/21/2023</th>
      <td className="fw-bold w-25">John Doe</td>
      <td className="fw-bold">Course 2</td>
      <td className="fw-bold" >2</td>
      <td className="fw-bold">$30</td>
      <td className="fw-bold">$3</td>
      <td className="fw-bold d-flex justify-content-between align-items-center">$63.00 <TbSpeakerphone /></td>
    </tr>
    <tr>
      <th className="fw-bold" >05/21/2023</th>
      <td className="fw-bold">John Doe</td>
      <td className="fw-bold">Course 2</td>
      <td className="fw-bold" >2</td>
      <td className="fw-bold">$30</td>
      <td className="fw-bold">$3</td>
      <td className="fw-bold">$63.00</td>
    </tr>
    <tr>
      <th className="fw-bold" >05/21/2023</th>
      <td className="fw-bold">John Doe</td>
      <td className="fw-bold">Course 2</td>
      <td className="fw-bold">2</td>
      <td className="fw-bold">$30</td>
      <td className="fw-bold">$3</td>
      <td className="fw-bold">$63.00</td>
    </tr>
  </tbody>
</table>

</div>
  <div className="d-flex gap-2 justify-content-end mt-3">
                  <button className="w-25 btn_primary text-light p-2 rounded fw-bold ">
                   Download
                  </button>
                </div>
          </div>
          </div>

      </main>
        <Footer />
    </>
  );
}
