import React from "react";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { Footer } from "../../components";
import { RiArrowGoBackLine } from "react-icons/ri";

export default function SignIn() {
  return (
    <>
      <Head>
        <title>Sign In Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container-fluid">
        <Link
          href="/"
          className="text-decoration-none p-4 d-flex gap-2 align-items-center text-dark"
        >
          <RiArrowGoBackLine />
          <p className="fw-bold m-0 p-0 ">Back to home</p>
        </Link>
        <div className="row">
          <div className="col-12 col-lg-6 d-flex justify-content-center align-items-center ">
            <div style={{ maxWidth: "400px", width: "100%" }}>
              {/* <h1 className="text-center mb-5">GSK</h1> */}
              <div className="d-flex justify-content-center mb-5">
                <Image
                  src="/assets/logo.png"
                  alt="Vercel Logo"
                  className=""
                  width={100}
                  height={50}
                  priority
                />
              </div>
              <div>
                <div className="d-flex justify-content-between mb-3">
                  <h4 className="text-secondary fw-bold">Sign In</h4>
                  <Link
                    href="/forgotpassword"
                    className="text-decoration-none d-flex gap-2"
                  >
                    <p className="fw-bold text_secondary">Forgot Password?</p>
                  </Link>
                </div>
                <div>
                  <select className="w-100 p-2 rounded outline-0 border border_gray text_gray mb-3 ">
                    <option>Student</option>
                    <option>Student</option>
                    <option>Student</option>
                  </select>
                  <input
                    type="text"
                    className="w-100 p-2 rounded outline-0 border border_gray text_gray  mb-3"
                    placeholder="Your Email"
                  />
                  <input
                    type="text"
                    className="w-100 p-2 rounded outline-0 border border_gray  text_gray mb-3"
                    placeholder="Password"
                  />
                  <button className="w-100 btn_primary text-light p-2 rounded fw-bold mt-3">
                    Sign In
                  </button>
                </div>
                <Link
                  href="/"
                  className="text-decoration-none d-flex gap-2 justify-content-center py-3"
                >
                  <p className="text-secondary fw-bold">Not yet Register?</p>
                  <p className="fw-bold text_secondary">Create account?</p>
                </Link>
              </div>
            </div>
          </div>
          <div
            className="col-12 col-lg-6 position-relative"
            style={{
              backgroundImage: 'url("/assets/auth_2.png")',
              height: "100vh",
              backgroundRepeat: "no-repeat",
              backgroundSize: "100% 100%",
            }}
          >
            <div style={{ position: "absolute", right: "0%", bottom: "7%" }}>
              <Image
                src="/assets/auth_girl_1.png"
                alt="Vercel Logo"
                className=""
                width={400}
                height={600}
                priority
              />
            </div>
          </div>
        </div>
        <Footer />
      </main>
    </>
  );
}
