import React, { useState } from 'react';
import Head from 'next/head';
import { Inter } from 'next/font/google';
import { Navbar, Footer } from '../../components';


export default function StudentRegistrationCCInfo() {
 
  return (
    <>
      <Head>
        <title>Student CC Info</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container-fluid">
     <Navbar isLogin={true}/>
        <div className="row">
        <div
            className="col-12 col-lg-5 position-relative"
            style={{
              backgroundImage: 'url("/assets/register_group.png")',
              height: '100vh',
              backgroundRepeat: 'no-repeat',
              backgroundSize: '100% 100%',
            }}
          >

          </div>
          <div className="col-12 col-lg-7 d-flex justify-content-center align-items-center ">
            <div className="w-75 p-5">
         
              <div>
             
                <h4 className="text-dark fw-bold">Who pays for tutoring?</h4>

                <div className="py-4">
                <select className="w-25 p-2 rounded outline-0 border border_gray text_gray mb-3 ">
                    <option>Select</option>
                    <option>Option 1</option>
                    <option>Option 2</option>
                  </select>
                  <h4 className="text-dark fw-bold p-0 m-0 text-center">OR</h4>
              
            
              </div>

              <h4 className="text-dark fw-bold pb-2">Add credit card information</h4>
              <input type="text" className="w-100 p-2 rounded outline-0 border border_gray text_gray  my-2" placeholder='Name of Credit Card'/>
              <input type="text" className="w-100 p-2 rounded outline-0 border border_gray text_gray  my-2" placeholder='Credit Card Number'/>

                      
              <div className="d-flex gap-2 my-2">
               <input type="text" className="w-100 p-2 rounded outline-0 border border_gray text_gray  mb-3" placeholder='CVV'/>
                  <input type="text" className="w-100 p-2 rounded outline-0 border border_gray text_gray  mb-3" placeholder='Expiration Date'/>
      
               </div>

               <div class="form-check">
                    <input
                      class="form-check-input"
                      type="checkbox"
                      value=""
                      id="flexCheckDefault"
                      
                    />
                    <label class="form-check-label" for="flexCheckDefault">
                    Save the payment information for future use
                    </label>
                  </div>
               <div className="d-flex gap-2 justify-content-center mt-3">

                  <button className="w-25 btn_primary text-light p-2 rounded fw-bold ">Continue</button>
                 
                  
                </div>
                <div className="d-flex gap-2 justify-content-center mt-3">

<button className="w-25 btn_secondary text-light p-2 rounded fw-bold ">I wil do this later</button>


</div>
                </div>
            </div>
            </div>
          </div>
         
        <Footer />
      </main>
    </>
  );
}
