import React, { useState, useEffect } from "react";
import Head from "next/head";
import { useRouter } from "next/router";
import { withRole } from "../../../utils/withAuthorization";
import ParentDetail from "../../../components/stripe/PaymentDetail/index";
import ParentLayout from "@/components/common/ParentLayout";

function CreditCardInfo() {
    //protection starts
    const nav = useRouter()
    // checking if user logged in starts
      if(typeof window !== 'undefined'){ // here we check if global object successfully loaded
        console.log('lol')
        useEffect(()=>{

          if(JSON.parse(window.localStorage.getItem('gkcAuth')).role === undefined) { //here we check if user signed in
            nav.push('/') 
          } else{
            if(JSON.parse(window.localStorage.getItem('gkcAuth')).role !== 'Instructor') { //here we check if user has role Instructor
              nav.push('/')
            }
          }

        },[])
      }
    // checking if user logged in ends

    //protection ends
  return (
    <>
      <Head>
        <title>Credit Card Information</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ParentLayout>
        <ParentDetail />
      </ParentLayout>
    </>
  );
}

export default withRole(CreditCardInfo, ["Parent"]);
