import React, { useState, useEffect } from "react";
import Head from "next/head";
import { Navbar, Footer } from "../../../components";
import Calendar from "react-calendar";
import { withRole } from '../../../utils/withAuthorization';
import { useRouter } from 'next/router';
import axios from "axios"
function RequestInterview() {
  const router = useRouter();
  const { instructorId } = router.query;
  const [profile, setProfile] = useState(null);
  const [value, onChange] = useState(new Date());
  const [events, setEvents] = useState([

    // Add more events as needed
  ]);
  const [unavailableDates, setUnavailableDates] = useState([

  ]);


  const getInfo = async () => {
    try {
      var typ = JSON.parse(window.localStorage.getItem("gkcAuth"));
      const res = await axios.get("http://34.227.65.157/user/logged-user-details", {
      headers: {
        Authorization: `Bearer ${typ.accessToken}`,
      },
    });
    console.log(res.data);
    setProfile(res.data);
    } catch (error) {
      console.error('Error fetching profile data:', error);
    }
  };



  useEffect(() => {

   
    getInfo();
    const fetchProfileData = async () => {
      var typ = JSON.parse(window.localStorage.getItem("gkcAuth"));
      console.log(typ)
      try {
        const res = await axios.get(`http://34.227.65.157/instructor/schedule-and-unavailable-days-iCal?instructorId={instructorId}`, {
        headers: {
          Authorization: `Bearer ${typ.accessToken}`,
        },
      });
      console.log(res.data);

    const calendarData = res.data;

    const events = [];
    const unavailableDays = [];

    const lines = calendarData.split('\n');

    let currentEvent = null;
    let currentFreeBusy = null;

    for (let i = 0; i < lines.length; i++) {
      const line = lines[i].trim();

      if (line.startsWith('BEGIN:VEVENT')) {
        currentEvent = {};
      } else if (line.startsWith('BEGIN:VFREEBUSY')) {
        currentFreeBusy = {};
      } else if (line.startsWith('UID:') && (currentEvent || currentFreeBusy)) {
        const uid = line.split(':')[1];
        if (currentEvent) {
          currentEvent.uid = uid;
        } else if (currentFreeBusy) {
          currentFreeBusy.uid = uid;
        }
      } else if (line.startsWith('DTSTART:') && currentEvent) {
        const dtStart = line.split(':')[1];
        const dateString = dtStart;
        const year = parseInt(dateString.slice(0, 4));
        const month = parseInt(dateString.slice(4, 6)) - 1; // Month is zero-based in JavaScript's Date object
        const day = parseInt(dateString.slice(6, 8));
        const date = new Date(year, month, day);
        currentEvent.dtStart =  date;

      } else if (line.startsWith('FREEBUSY;FBTYPE=BUSY:') && currentFreeBusy) {
        const [start, end] = line.split(':')[1].split('/');

        const dateString = start;
        const year = parseInt(dateString.slice(0, 4));
        const month = parseInt(dateString.slice(4, 6)) - 1; // Month is zero-based in JavaScript's Date object
        const day = parseInt(dateString.slice(6, 8));
        const date = new Date(year, month, day);
        currentFreeBusy.start = date;
        currentFreeBusy.end = end;
      } else if (line.startsWith('END:VEVENT')) {
        if (currentEvent) {
          events.push(currentEvent);
          currentEvent = null;
        }
      } else if (line.startsWith('END:VFREEBUSY')) {
        if (currentFreeBusy) {
          unavailableDays.push(currentFreeBusy);
          currentFreeBusy = null;
        }
      }
    }

    // this.setState({ events, unavailableDays });
    setUnavailableDates(unavailableDays)
    setEvents(events)
    console.log(events, unavailableDays)
  } catch (error) {
    console.error('Error fetching profile data:', error);
  }
};

fetchProfileData()
  }, []);


  const tileContent = ({ date, view }) => {
    if (view === 'month') {
      const event = events.find((event) => event.dtStart.getTime() === date.getTime());
      if (event) {
        return 'event-day';
      }
    }

    return null;
  };

  
  const tileDisabled = ({ date }) => {
    return unavailableDates.some((disabledDay) => date.toDateString() === disabledDay.start.toDateString());
  };
  return (
    <>
      <Head>
        <title>Request Interview</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar isLogin={true} />
      <main className="container-fluid">
      <div
          className="row"
          style={{ minHeight: "90vh" }}
        >
          <div className="col-12 col-lg-6 pt-5">
          <p className="fw-bold text-center">
              Schedule Interview with John Doe
            </p>
            <Calendar onChange={onChange} value={value} 
              tileDisabled={tileDisabled}
              tileClassName={tileContent} />
          </div>
          <div className="col-12 col-lg-6 pt-5">
          <p className="fw-bold text-center text-white">I</p>
            <div className="shadow rounded py-5">
              <div
                className="d-flex justify-content-between gap-4 px-3"
                style={{ minHeight: "400px" }}
              >
                <div className="w-100 ">
                  <p className="p-0 m-0 fw-bold pb-2">Select time</p>
                  <div className="border rounded p-2 px-3">
                    <p className="p-0 m-0 py-1 fw-bold">7:00 am</p>
                    <p className="p-0 m-0 py-1 fw-bold">7:15 am</p>
                    <p className="p-0 m-0 py-1 fw-bold">7:30 am</p>
                    <br />
                    <br />
                    <br />
                    <br />
                    <br />
                    <br />
                    <br />
                    <br />
                    <br />
                    <p className="p-0 m-0 py-1 fw-bold">4:45 pm</p>
                    <p className="p-0 m-0 py-1 fw-bold">5:00 pm</p>
                  </div>
                </div>
                <div className=" w-100">
                  <p className="p-0 m-0 fw-bold text-center py-2">
                    Your information
                  </p>
                  <h6 className="text-dark fw-bold">Course:</h6>

                  <div className="py-2">
                    <select className="w-25 p-2 rounded outline-0 border border_gray  mb-3 ">
                      <option>Select</option>
                      <option>Option 1</option>
                      <option>Option 2</option>
                    </select>
                  </div>

                  <h6 className="text-dark fw-bold">Mode:</h6>

                  <div className="py-2">
                    <select className="w-25 p-2 rounded outline-0 border border_gray  mb-3 ">
                      <option>Select</option>
                      <option>Option 1</option>
                      <option>Option 2</option>
                    </select>
                  </div>

                  <h6 className="text-dark fw-bold">Skill:</h6>

                  <p className="text-dark fw-bold py-2">{profile?.grade.name}</p>

                  <h6 className="text-dark fw-bold">Grade:</h6>

                  <p className="text-dark fw-bold py-2">{profile?.grade.name}</p>
                </div>
              </div>
              <div className="d-flex gap-2 justify-content-center pt-5">
                <button className="w-25 btn_primary text-light p-2 rounded fw-bold ">
                  Schedule
                </button>
              </div>
            </div>
          </div>
          </div>


     
      </main>
      <Footer />
    </>
  );
}


export default withRole(RequestInterview, ['Student']);
