import React, { useState } from 'react';
import Head from 'next/head';
import { TutorNavbar, Footer } from '../../../components';
import { useRouter } from 'next/router';
import { withRole } from '../../../utils/withAuthorization';
import Link from 'next/link';

function BankInfo() {
  const navigation = useRouter();
  const [showPayoneerInput, setShowPayoneerInput] = useState(false);
  const [showPayPalInput, setShowPayPalInput] = useState(false);

  return (
    <>
      <Head>
        <title> Instructor CC Info </title>{' '}
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>{' '}
      <TutorNavbar isLogin={true} />{' '}
      {/* <main className="container-fluid d-flex flex-column justify-content-between min-vh-100">
        <div className="d-flex justify-content-center align-items-center p-5">
          <div className="col-12 col-lg-7">
            <div>
              <div>
                <h4 className="text-dark fw-bold pb-2 text-center mt-5 mb-5">Tell us where to deposit your payments</h4>{" "}
                <select className="w-100 p-2 rounded outline-0 border border_gray  mb-3 ">
                  <option> Checking </option> <option> Saving </option>{" "}
                </select>{" "}
                <input
                  type="text"
                  className="w-100 p-2 rounded outline-0 border border_gray   my-2"
                  placeholder="Name on Credit Card"
                />
                <input
                  type="text"
                  className="w-100 p-2 rounded outline-0 border border_gray   my-2"
                  placeholder="Credit Card Number"
                />
                <div className="d-flex gap-2 my-2">
                  <input
                    type="text"
                    className="w-100 p-2 rounded outline-0 border border_gray   mb-3"
                    placeholder="CVV"
                  />
                  <input
                    type="text"
                    className="w-100 p-2 rounded outline-0 border border_gray   mb-3"
                    placeholder="Expiration Date"
                  />
                </div>
                <div className="d-flex gap-2 justify-content-center mt-3">
                  <button
                    className="w-50 btn_primary text-light p-2 rounded fw-bold "
                    onClick={() => navigation.push("/")}
                  >
                    Update{" "}
                  </button>{" "}
                </div>
              </div>{" "}
            </div>{" "}
          </div>{" "}
        </div>
        <Footer />
      </main> */}
      <div className="w-100">
        <h4
          style={{ marginTop: '120px' }}
          className="text-dark fw-bold pb-2 text-center"
        >
          Tell us where to deposit your payments
        </h4>
        <div className="d-flex mt-5 justify-content-center align-items-center flex-column">
          <div className="d-flex align-items-center gap-5 justify-content-center">
            <p style={{ width: '100px' }} className="fw-bold">
              Payoneer
            </p>
            <button
              onClick={() => setShowPayoneerInput(!showPayoneerInput)}
              style={{ backgroundColor: '#f48342' }}
              className="py-2 px-4 fw-bold text-white rounded"
            >
              Setup
            </button>
          </div>
          {showPayoneerInput && (
            <input
              placeholder="Enter Payoneer info"
              className="mt-3 fw-bold border-2 border-dark p-1"
            ></input>
          )}
          <div className="mt-5 d-flex gap-5 align-items-center justify-content-center">
            <p style={{ width: '100px' }} className="fw-bold">
              PayPal
            </p>
            <button
              onClick={() => setShowPayPalInput(!showPayPalInput)}
              style={{ backgroundColor: '#f48342' }}
              className="py-2 px-4 fw-bold text-white rounded"
            >
              Setup
            </button>
          </div>
          {showPayPalInput && (
            <input
              placeholder="Enter PayPal info"
              className="mt-3 fw-bold border-2 border-dark p-1"
            ></input>
          )}
          <div className="">
            <button
              style={{ marginTop: '80px', backgroundColor: '#f48342' }}
              className="text-light p-2 w-100 rounded fw-bold  bg-gray-300"
            >
              Continue
            </button>
            <Link href="/" className="text-decoration-none">
              <p className="text-secondary mt-4 fw-bold">I'll do this later.</p>
            </Link>
          </div>
        </div>
      </div>
    </>
  );
}

export default withRole(BankInfo, ['Instructor']);
