import React, { useState } from "react";
import Head from "next/head";
import { TutorNavbar, Footer } from "../../../components";
import { useRouter } from "next/router";
import { withRole } from "../../../utils/withAuthorization";

function BankInfo() {
  const navigation = useRouter();

  return (
    <>
      <Head>
        <title> Instructor CC Info </title>{" "}
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>{" "}
      <TutorNavbar isLogin={true} />{" "}
      <main className="container-fluid d-flex flex-column justify-content-between min-vh-100">
        <div className="d-flex justify-content-center align-items-center p-5">
          <div className="col-12 col-lg-7">
            <div>
              <div>
                {" "}
                {/* <h4 className="text-dark fw-bold">Who pays for tutoring?</h4>
                            <div className="py-4">
                              <select className="w-25 p-2 rounded outline-0 border border_gray  mb-3 ">
                                <option>Select</option>
                                <option>Option 1</option>
                                <option>Option 2</option>
                              </select>
                              <h4 className="text-dark fw-bold p-0 m-0 text-center">OR</h4>
                            </div> */}
                <h4 className="text-dark fw-bold pb-2 text-center mt-5 mb-5">Funds Transfer information </h4>{" "}
                <select className="w-100 p-2 rounded outline-0 border border_gray  mb-3 ">
                  <option> Checking </option> <option> Saving </option>{" "}
                </select>{" "}
                <input
                  type="text"
                  className="w-100 p-2 rounded outline-0 border border_gray   my-2"
                  placeholder="Name on Credit Card"
                />
                <input
                  type="text"
                  className="w-100 p-2 rounded outline-0 border border_gray   my-2"
                  placeholder="Credit Card Number"
                />
                <div className="d-flex gap-2 my-2">
                  <input
                    type="text"
                    className="w-100 p-2 rounded outline-0 border border_gray   mb-3"
                    placeholder="CVV"
                  />
                  <input
                    type="text"
                    className="w-100 p-2 rounded outline-0 border border_gray   mb-3"
                    placeholder="Expiration Date"
                  />
                </div>
                {/* <div className="form-check">
                              <input
                                className="form-check-input"
                                type="checkbox"
                                value=""
                                id="flexCheckDefault"
                              />
                              <label className="form-check-label" for="flexCheckDefault">
                                Save the payment information for future use
                              </label>
                            </div> */}{" "}
                <div className="d-flex gap-2 justify-content-center mt-3">
                  <button
                    className="w-50 btn_primary text-light p-2 rounded fw-bold "
                    onClick={() => navigation.push("/")}
                  >
                    Update{" "}
                  </button>{" "}
                </div>
              </div>{" "}
            </div>{" "}
          </div>{" "}
        </div>
        <Footer />
      </main>{" "}
    </>
  );
}

export default withRole(BankInfo, ["Instructor"]);
