import React from 'react';
import Link from 'next/link';

const PrivacyPolicy = () => {
  return (
    <div className="container mx-auto px-4 py-12">
      <h1 className="text-3xl font-bold mb-4 pt-5">Privacy Policy</h1>
      <h2 className="text-3xl font-bold mb-4 pt-5">Effective: September 26, 2023</h2>
      <p className="text-lg">
        This Privacy Policy outlines your right to privacy and how GeekKidsCode, a web application owned and operated by Greinchville Solutions LLC, based in Houston Texas and registered in the state of Texas, stores and publishes information collected from visitors (each, a “Visitor”) of its "https://www.geekkidscode.com" website and any derivative or affiliated websites on which this Privacy Policy is posted (collectively, the “Website”). This Privacy Policy is a supplement to the GeekKidsCode Terms of Use (the “Agreement”), including any other supplemental terms, guidelines and/or policies. Greinchville Solutions LLC reserves the right, at its discretion, to change this Privacy Policy at any time. 
      </p>
      <p className="text-lg">
        As a user of GeekKidsCode, you understand that you have the affirmative obligation to check this Privacy Policy periodically for changes, and you hereby agree to periodically review this Privacy Policy for such changes. The continued use of the Website following the posting of changes to this Privacy Policy constitutes an acceptance of those changes. 
      </p>

      <h2 className="text-3xl font-bold mb-4 pt-5">Privacy </h2>
      <p>
        Greinchville Solutions LLC believes that every GeekKidsCode Visitor should know how it utilizes the information collected from Visitors. GeekKidsCode may collect personally identifiable information from children under 18 years of age online. However, parents should note that no information collected, personally identifiable or not, is sold to any third party vendor. Please note that the Website may contain links to other websites. These linked sites may not be operated or controlled by Greinchville Solutions LLC. Greinchville Solutions LLC is not responsible for the privacy practices of these or any other websites, and you access these websites entirely at your own risk. Greinchville Solutions LLC recommends that you review the privacy practices of any other websites that you choose to visit, if they are available. 
      </p>
      <p>
        Greinchville Solutions LLC is based, and GeekKidsCode is hosted, in the United States of America. If a Visitor is from the European Union or other regions of the world with laws governing data collection and use that may differ from U.S. law and Visitor is registering an account on the Website, visiting the Website, purchasing products or services from GeekKidsCode, or otherwise using the Website, please note that any personally identifiable information that Visitor provides to GeekKidsCode will be transferred to the United States. Any such personally identifiable information provided will be processed and stored in the United States by GeekKidsCode or a service provider such as Amazon Web Service (“AWS”). By providing your personally identifiable information, Visitor hereby specifically and expressly consents to such transfer and processing and the uses and disclosures set forth herein. 
      </p>
      <p>
        GeekKidsCode is hosted on AWS, a company based in the United States. All information provided by Visitors are stored in cloud servers owned and operated by AWS
      </p>

      <h2 className="text-3xl font-bold mb-4 pt-5">The Information GeekKidsCode Collects </h2>
      <p>
        Greinchville Solutions LLC may collect personally identifiable information from Visitors in a variety of ways. Personally identifiable information may include, without limitation, (i) contact data (such as a Visitor’s name, mailing and email addresses);(ii) demographic data (such as a Visitor’s zip code, address, location, schools attended, or school interests); (iii) internet and network data (such as a Visitor’s browser type, language, referring site, subsequent site, frequency of visits, and date/time of each Visitor’s request); (iv) Visitor’s information: a Visitor communicates with GeekKidsCode by email or otherwise, posts, any comments or any other content on or to the Website, posts messages to any forums, completes online forms, surveys or entries, provides articles, reviews, or blog posts, or otherwise interacts with or uses the features on the Website, any information provided in such communications  GeekKidsCode may be collected by Greinchville Solutions LLC); (v) analytics information (via third-party services that may use web logs, web beacons, cookies, or other tracking technologies, as well as information about how Visitors use the Website, for example, by tracking the number of unique views received by the pages of the Website, or the domains and IP addresses from which Visitors originate). While not all of the information that Greinchville Solutions LLC collects from Visitors of GeekKidsCode is personally identifiable, it may be associated with personally identifiable information that Visitors provide through the GeekKidsCode Website or otherwise. 
      </p>
      <p>
        Greinchville Solutions LLC may use “cookies” or “web beacons” to track how Visitors use the GeekKidsCode Website. A cookie is a software component that can be stored on Visitors’ computing device and used to recognize Visitors if they visit the Website again. Visitors may adjust their web browser software if they do not wish to accept cookies. GeekKidsCode does not currently recognize “do not track” signals. GeekKidsCode may use third party advertising networks to serve advertisements on the Website. The cookies received with banner advertisements served by these networks are used to collect and build anonymous behavioral profiles by these companies to deliver targeted advertisements and tracking referrals, and GeekKidsCode generally does not have access to this information. We may implement Google Analytics features that use Display Advertising information for Google Analytics Demographics and Interest Reporting. You can opt-out of Google Analytics for Display Advertising, to prevent your data from being used by Google Analytics, by going to the Google Analytics opt-out page. We, along with third-party vendors (including Google), use first-party cookies (such as the Google Analytics cookies) and third-party cookies (such as the DoubleClick cookies) to report how your ad impressions, other uses of ad services, and interactions with these ad impressions and ad services are related to visits to our website. You can read more about the cookies used by Google Analytics advertising features, by going to the Google Analytics Privacy Policy page. 
      </p>

      <h2 className="text-3xl font-bold mb-4 pt-5">How GeekKidsCode Uses Information </h2>
      <p>
        Greinchville Solutions LLC may use personally identifiable information collected through the GeekKidsCode Website for the specific purposes for which the information was collected, to contact Visitors regarding products and services offered by GeekKidsCode, its parent (Greinchville Solutions LLC), subsidiary and other related companies and its trusted affiliates, independent contractors and business partners, and otherwise to enhance Visitors’ experience with GeekKidsCode and such affiliates, independent contractors and business partners, and for such other purposes as deemed reasonably necessary or desirable to Visitors generally. Greinchville Solutions LLC may also use information collected through the GeekKidsCode Website for research regarding the effectiveness of the Website and the business planning, marketing, and advertising for GeekKidsCode, its trusted affiliates, independent contractors and business partners. 
      </p>
      <h2 className="text-3xl font-bold mb-4 pt-5">Disclosure of Information </h2>
      <p>
        Greinchville Solutions LLC may disclose personally identifiable information collected from Visitors GeekKidsCode website (including within the past twelve (12) months: (i) to any service providers, contractors, or third-party vendors for performance of the Site and/or the services; (ii) to its subsidiary and other related companies, trusted affiliates, independent contractors and business partners who will use the information for the purposes outlined above, (iii) as necessary to provide the services offered by Greinchville Solutions LLC and to provide the GeekKidsCode Website itself, (iv) for the specific purposes for which the information was collected; (v) at the request of law enforcement or governmental agencies or in response to subpoenas, court orders or other legal process, to establish, protect or exercise Greinchville Solutions LLC’s legal or other rights or to defend against a legal claim or as otherwise required or allowed by law, or in order to protect the rights, property or safety of a Visitor or any other person; (vi) to investigate or prevent a violation by Visitor of any contractual or other relationship with GeekKidsCode website or the perpetration of any illegal or harmful activity; (vii) in connection with or in contemplation of a sale of its assets or business or a merger, consolidation or other reorganization of its business. Greinchville Solutions LLC may also disclose aggregate, anonymous data based on information collected from Visitors to investors and potential partners. 
      </p>
      <h2 className="text-3xl font-bold mb-4 pt-5">Personal Information Provided as Part of Visitor Submission(s) </h2>
      <p>
        If a Visitor includes such Visitor’s personally identifiable information as part of the Visitor submission that such Visitor posts to the Website, such information may be made available to any parties using the Website and/or such Visitor submission. GeekKidsCode does not edit or otherwise remove such information from Visitor submission before it is posted on the Website. If a Visitor does not wish to have such Visitor’s personally identifiable information made available in this manner, such Visitor must remove any such information from the Visitor submission before posting. Visitor contact information (which may include, without limitation, a Visitor’s email address) may be included with any Visitor submission that a Visitor posts via the Website. Greinchville Solutions LLC is not liable for any damages caused or incurred due to personally identifiable information made available in the foregoing manners. 
      </p>
      <h2 className="text-3xl font-bold mb-4 pt-5">Security of Information </h2>
      <p>
        Information about Visitors that is maintained on AWS is protected using industry standard security measures. However, no security measures are perfect or impenetrable, and GeekKidsCode cannot guarantee that the information submitted to, maintained on or transmitted from its systems will be completely secure. GeekKidsCode is not responsible for the circumvention of any privacy settings or security measures relating to the Website by any Visitors or third parties. We store the information collected as described in this Privacy Policy for as long as you are a User of the Site and/or as necessary to fulfill the purpose(s) for which the information was collected, to provide services through the Site, to resolve disputes, to pursue legitimate business purposes, to enforce our agreements, to establish legal defenses, to prevent fraud, and to comply with applicable laws. 
      </p>
      <h2 className="text-3xl font-bold mb-4 pt-5">Correcting, Updating, Accessing or Removing Personal Information </h2>
      <p>
        If a Visitor’s personally identifiable information changes, or if a Visitor no longer desires to receive non-account specific information from GeekKidsCode, Greinchville Solutions LLC will endeavor to provide a way to correct, update and/or remove that Visitor’s previously-provided personal data. This can be done by submitting a request to services@geekkidscode.com. Additionally, you may request access to the personally identifiable information as collected on GeekKidsCode website by sending a request as set forth above. Please note that in certain circumstances, Greinchville Solutions LLC may not be able to completely remove a Visitor’s information from its systems. For example, Greinchville Solutions LLC may retain a Visitor’s personal information for legitimate business purposes, if it may be necessary to prevent fraud or future abuse, for account recovery purposes, if required by law or as retained in GeekKidsCode’s data backup systems or cached or archived pages. All retained personally identifiable information will continue to be subject to the terms of the Privacy Policy to which the Visitor has previously agreed. For state-specific information or related rights, please see the state-specific sections below. 
      </p>
      <h2 className="text-3xl font-bold mb-4 pt-5">Your California Privacy Rights </h2>
      <p>
        Subject to certain limitations, the California Consumer Privacy Act (CCPA) provides California consumers the right to: request disclosure about what personal information we collect, use, disclose, and sell; request to delete their personal information; opt out of any “sale” of personal information; and not be discriminated against for exercising such rights. California consumers may make a request pursuant to their rights under the CCPA by sending a request to services@geekkidscode.com. We will verify your request using information provided in the request, as compared against the information associated with your account, including verification of the email address that was listed in the request email. We may need to request additional information in order to verify your identity. Depending on the type of request you make, we may require a signed declaration stating that you are the individual about whom personal information is being requested. If you use an authorized agent to submit a request, then we may require that the authorized agent provide proof of your written permission, and that you verify your identity directly with us. We have explained the privacy practices in full in the foregoing sections of this Privacy Policy. Further, we do not consider the ways we share or disclose your information to comprise the sale of your information. 
      </p>
      <h2 className="text-3xl font-bold mb-4 pt-5">Your Nevada Privacy Rights </h2>
      <p>
        Nevada Revised Statute Section 603A permits a user that resides in Nevada the right to submit a verified request that Greinchville Solutions LLC not sell such user’s covered information. Greinchville Solutions LLC does not sell any covered information gathered on the GeekKidsCode website as defined under Nevada Revised Statute Section 603A. However, if you are a Nevada resident, then you may still submit a verified request via services@geekkidscode.com. We will verify your request using information associated with your account, including email address, and may need to request additional information. 
      </p>
      <h2 className="text-3xl font-bold mb-4 pt-5">Changes to this Policy </h2>
      <p>
        We may update this privacy policy to reflect changes to our information practices. If we make any material changes, then we may notify you by email (sent to the e-mail address specified in your account) or by means of a notice on this Site prior to the change becoming effective. We encourage you to periodically review this page for the latest information on our privacy practices. Your continued use of the Site after any such change signifies your acceptance of any changes. 
      </p>
      <h2 className="text-3xl font-bold mb-4 pt-5">Contacting Greinchville Solutions LLC for GeekKidsCode Related Privacy Policy </h2>
      <p>
        If you have any questions or comments about this Privacy Policy, you may contact Greinchville Solutions LLC at: info@geekkidscode.com

      </p>
    </div>
  );
};

export default PrivacyPolicy;