import React, { useState } from "react";
import Head from "next/head";
import { Inter } from "next/font/google";
import { Navbar, Footer } from "../../components";

export default function StudentRegistrationCCPay() {
  return (
    <>
      <Head>
        <title>Student Setting Pay Info</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container-fluid">
        <Navbar isLogin={true} />
          <div className="w-50 m-auto d-flex justify-content-center align-items-center ">
            <div className="w-75 p-5" style={{minHeight:"100vh"}}>
            <h5 className="text-dark fw-bold text-center py-4">
                  Credit Card Information
                </h5>
              <div>
     
                <input
                  type="text"
                  className="w-100 p-2 rounded outline-0 border border_gray text_gray  my-2"
                  placeholder="Name on Credit Card"
                />
                <input
                  type="text"
                  className="w-100 p-2 rounded outline-0 border border_gray text_gray  my-2"
                  placeholder="Credit Card Number"
                />

                <div className="d-flex gap-2 my-2">
                  <input
                    type="text"
                    className="w-100 p-2 rounded outline-0 border border_gray text_gray  mb-3"
                    placeholder="CVV"
                  />
                  <input
                    type="text"
                    className="w-100 p-2 rounded outline-0 border border_gray text_gray  mb-3"
                    placeholder="Expiration Date"
                  />
                </div>

               
         
                <div className="d-flex gap-2 justify-content-center mt-3">
                  <button className="w-25 btn_primary text-light p-2 rounded fw-bold ">
                    Say
                  </button>
                </div>
         
              </div>
            </div>
          </div>

        <Footer />
      </main>
    </>
  );
}
