import React, {useState, useEffect} from "react";
import Head from "next/head";
import Link from "next/link";
import { Navbar, Footer } from "../../../components";
import { BsCheck2Circle } from "react-icons/bs";
import {useRouter} from "next/router"

export default function RegisterStudent() {
  const [email, setEmail] = useState("");
  const navigation = useRouter();
  const onContinue = () => {
   if(email === "parent"){
    navigation.push("/auth/parentccinfo")

  }
  else {

    navigation.push("/auth/registrationgrade")
  }
  }

  useEffect(() => {
    const value = JSON.parse(window.localStorage.getItem("userType"));
    setEmail(value);
  }, []);
  return (
    <>
      <Head>
        <title>Auth | Student Registration</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container-fluid d-flex flex-column justify-content-between  min-vh-100">
        <Navbar isLogin={true} />
        <div className="row">
          <div
            className="col-12 col-lg-6 position-relative  d-none d-md-block "
            style={{
              backgroundImage: 'url("/assets/register_group.png")',
              height: "100vh",
              backgroundRepeat: "no-repeat",
              backgroundSize: "100% 100%",
            }}
          ></div>
          <div className="col-12 col-lg-6 d-flex justify-content-center align-items-center ">
            <div className="w-100 w-md-75 p-5">
              <div>
                <div className="d-flex justify-content-between align-items-center mb-3">
                  <h4 className="text-secondary fw-bold text-capitalize" >{email}</h4>
                  <p className="bg_secondary text-white p-2 rounded d-flex align-items-center gap-2 fw-bold">
                    <BsCheck2Circle style={{ fontSize: "22px" }} />
                    {email}@123.com
                  </p>
                </div>
                <div>
                  <input
                    type="text"
                    className="w-100 p-2 rounded outline-0 border border_gray text_gray  mb-3"
                    placeholder="Enter Parent/Guardian 1 Email"
                  />
                  <input
                    type="text"
                    className="w-100 p-2 rounded outline-0 border border_gray text_gray "
                    placeholder="Enter Parent/Guardian 2 Email"
                  />
                  <div className="py-2">
                    <label className="text_gray m-0">
                      This is to link your account to your parent/guardian
                    </label>
                    <br />
                    <label className="text_gray m-0">
                      We do not have any record of parent 2
                    </label>
                  </div>{" "}
                  <div className="d-flex   flex-md-nowrap flex-wrap gap-2">
                    <input
                      type="text"
                      className="w-100 p-2 rounded outline-0 border border_gray text_gray  mb-3"
                      placeholder="First Name"
                    />
                    <input
                      type="text"
                      className="w-100 p-2 rounded outline-0 border border_gray text_gray  mb-3"
                      placeholder="Last Name"
                    />
                  </div>
                  <div className="d-flex  flex-md-nowrap flex-wrap gap-2">
                    <input
                      type="password"
                      className="w-100 p-2 rounded outline-0 border border_gray text_gray  mb-3"
                      placeholder="Password"
                    />
                    <input
                      type="password"
                      className="w-100 p-2 rounded outline-0 border border_gray text_gray  mb-3"
                      placeholder="Confirm Password"
                    />
                  </div>
                  <div class="form-check">
                    <input
                      class="form-check-input"
                      type="checkbox"
                      value=""
                      id="flexCheckDefault"
                    />
                    <label class="form-check-label" for="flexCheckDefault">
                      I agree to the Terms of Use and Privacy Policy of GKC
                    </label>
                  </div>
                  <div className="d-flex flex-wrap gap-2 justify-content-between mt-3">
                    <button className="w-50 btn_primary text-light p-2 rounded fw-bold " onClick={onContinue}>
                      Continue
                    </button>
                    <Link
                      href="/"
                      className="text-decoration-none d-flex gap-2 justify-content-center"
                    >
                      <p className="text-secondary fw-bold">
                        Already have an Account?
                      </p>
                      <p className="fw-bold text_secondary">login</p>
                    </Link>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <Footer />
      </main>
    </>
  );
}
