import React from "react";
import Head from "next/head";
import { TutorNavbar, Footer } from "../../../components";
import { BsFillSendFill } from "react-icons/bs";

export default function InstructorMessaging() {
  return (
    <>
      <Head>
        <title>Instructor Messaging</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <TutorNavbar isLogin={true} />
      <main className="container">
        <br />
        <br />
        <br />

        <div className="row" style={{minHeight:"90vh"}} >
        <div className="col-12 col-lg-3">
        <ul className="p-0 m-0" style={{ listStyle: "none" }}>
              <li className="p-0 m-0 fw-bold bg-light p-3 my-3 rounded ">
                John Doe
              </li>
              <li className="p-0 m-0 fw-bold  p-3 my-3 rounded ">Jane Khan</li>
              <li className="p-0 m-0 fw-bold  p-3 my-3 rounded ">Liz Gibz</li>
              <li className="p-0 m-0 fw-bold  p-3 my-3 rounded ">
                Scott Lopez
              </li>
            </ul>
       </div>

       <div className="col-12 col-lg-9">
       <div
            className=" border d-flex flex-column justify-content-between p-3 rounded"
            style={{ height: "600px" }}
          >
            <div className=" p-3" style={{ minHeight: "400px" }}>
              <div className="py-1 text-end">
                <p className="p-0 m-0 fw-bold">
                  lorem ipsum dolor sit amet, consectetur adipis.
                </p>
                <small className="p-0 m-0">John Doe 4/11/23 8:15am</small>
              </div>

              <div className="py-1">
                <p className="p-0 m-0 fw-bold">
                  lorem ipsum dolor sit amet, consectetur adipis.
                </p>
                <small className="p-0 m-0">John Doe 4/11/23 8:15am</small>
              </div>
            </div>
            <div className=" d-flex align-items-center px-2 gap-2">
              <input
                type="text"
                placeholde=""
                className="border  p-2 rounded flex-fill"
              />{" "}
              <BsFillSendFill className="h3 p-0 m-0" />
            </div>
            </div>

        </div>

        </div>
 

      </main>
        <Footer />
    </>
  );
}
