import React, {useState} from "react";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { Footer } from "../../../components";
import { RiArrowGoBackLine } from "react-icons/ri";
import {useRouter} from "next/router"
export default function ForgotPassword() {
  
const [showActivation, setShowActivation] = useState(false);
  const navigation = useRouter();
  const onContinue = () => {
    if (showActivation) {
      return navigation.push("/auth/signin");
    }
    setShowActivation(true);
  };

  return (
    <>
      <Head>
        <title>Auth | Change Password</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container-fluid d-flex flex-column justify-content-between  min-vh-100">
        <Link
          href="/"
          className="text-decoration-none p-4 d-flex gap-2 align-items-center text-dark"
        >
          <RiArrowGoBackLine />
          <p className="fw-bold m-0 p-0 ">Back to home</p>
        </Link>
        <div className="row">
          <div className="col-12 col-lg-6 d-flex justify-content-center align-items-center ">
            <div style={{ maxWidth: "380px", width: "100%" }}>
            <div
          className={`d-flex flex-column justify-content-center  pt-5`}
        >
          <div className="">
            <input
              className="form-control my-3 1-100"
              type="password"
              placeholder="Old password"
            />
            <input
              className="form-control my-3 w-100"
              type="password"
              placeholder="New password"
            />
            <input
              className="form-control my-3 w-100"
              type="password"
              placeholder="Confirm new password"
            />
            {showActivation ? (
              <input
                className="form-control my-3 w-100"
                type="text"
                placeholder="Verification code"
              />
            ) : null}

       
            <button onClick={onContinue} className="w-100 btn_primary text-light p-2 rounded fw-bold mt-3">
                   Continue
                  </button>
            <div>
              {showActivation ? (
                <p>Great!!! password updated successfully</p>
              ) : null}
            </div>
          </div>
        </div>
        </div>
           
          </div>
          <div
            className="col-12 col-lg-6 position-relative d-none d-md-block"
            style={{
              backgroundImage: 'url("/assets/auth_2.png")',
              height: "100vh",
              backgroundRepeat: "no-repeat",
              backgroundSize: "100% 100%",
            }}
          >
            <div style={{ position: "absolute", right: "0%", bottom: "7%" }}>
              <Image
                src="/assets/auth_boy_1.png"
                alt="Vercel Logo"
                className=""
                width={600}
                height={600}
                priority
              />
            </div>
          </div>
        </div>
        <Footer />
      </main>
    </>
  );
}




     