import React, { useState, useEffect } from "react";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { Footer, Navbar } from "../../../components";
import { RiArrowGoBackLine } from "react-icons/ri";
import { useRouter } from "next/router";
import GetUserDetail from "../../../services/user/GetUserDetail";
import GetAuthCode from "@/services/Auth/GetAuthCode";
import VerifyAuthCode from "@/services/Auth/VerifyAuthCode";
import ChangePassword from "@/services/user/ChangePassword";
export default function ForgotPassword() {
  const [data, setData] = useState({
    email: "",
    verifyCode: "",
    oldPassword: "",
    newPassword: "",
    confirmPassword: "",
  });
  const [userDetail, setUserDetail] = useState({});
  const [showSuccess, setSuccess] = useState(false);
  const [showActivation, setShowActivation] = useState(false);
  const [err, setErr] = useState("");
  const navigation = useRouter();
  const onContinue = () => {
    setShowActivation(true);
    GetAuthCode(userDetail?.email);
  };

  const changePassword = async () => {
    try {
      let { verifyCode, confirmPassword, ...otherProps } = data;
      let responseChangePassword = await ChangePassword({
        ...otherProps,
        email: userDetail.email,
      });

      setSuccess(true);
    } catch (err) {
      setErr("Incorrect Old Password");
      console.log("err", err);
    }
  };

  const verifyCode = async () => {
    try {
      setErr("");
      let res = await VerifyAuthCode({
        email: userDetail.email,
        code: data?.verifyCode,
      });
      if (res.status == 202) {
        changePassword();
      }
      console.log("res", res);
    } catch (err) {
      setErr("Incorrect verification code");
      console.log("err", err);
    }
  };
  const onChange = (e) => {
    setData({ ...data, [e.target.name]: e.target.value });
  };

  const fetchUser = async () => {
    try {
      let user = await GetUserDetail();
      setUserDetail(user?.data?.userDetails);
    } catch (err) {
      console.log("err", err);
    }
  };

  useEffect(() => {
    fetchUser();
  }, []);
  let isValid =
    data.newPassword != "" &&
    data.newPassword == data.confirmPassword &&
    data.oldPassword != ""
      ? true
      : false;
  return (
    <>
      <Head>
        <title>Auth | Change Password</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className="container-fluid d-flex flex-column justify-content-between  min-vh-100">
        <Link
          href="/"
          className="text-decoration-none p-4 d-flex gap-2 align-items-center text-dark"
        >
          <RiArrowGoBackLine />
          <p className="fw-bold m-0 p-0 ">Back to home</p>
        </Link>
        <div className="d-flex justify-content-center">
          <h1>Change Password</h1>
        </div>
        <div className="d-flex justify-content-center">
          <div className="col-12 col-lg-6 d-flex justify-content-center align-items-center">
            <div style={{ maxWidth: "380px", width: "100%" }}>
              <div
                className={`d-flex flex-column justify-content-center pt-5`}
              >
                <div className="">
                  <input
                    name="oldPassword"
                    value={data.oldPassword}
                    className="form-control my-3 1-100"
                    type="password"
                    placeholder="Old password"
                    onChange={onChange}
                  />
                  <input
                    name="newPassword"
                    value={data.newPassword}
                    className="form-control my-3 w-100"
                    type="password"
                    placeholder="New password"
                    onChange={onChange}
                  />
                  <input
                    name="confirmPassword"
                    value={data.confirmPassword}
                    className="form-control my-3 w-100"
                    type="password"
                    placeholder="Confirm new password"
                    onChange={onChange}
                  />
                  {showActivation ? (
                    <input
                      name="verifyCode"
                      onChange={onChange}
                      className="form-control my-3 w-100"
                      type="text"
                      placeholder="Verification code"
                    />
                  ) : null}

                  {err ? <p style={{ color: "red" }}>{err}</p> : null}

                  <button
                    disabled={isValid ? false : true}
                    onClick={() =>
                      showActivation ? verifyCode() : onContinue()
                    }
                    className="w-100 btn_primary text-light p-2 rounded fw-bold mt-3"
                  >
                    Continue
                  </button>
                  <div>
                    {showSuccess ? (
                      <p className="mt-3 d-flex justify-content-center text-secondary">Great! Password updated successfully ✔️</p>
                    ) : null}
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <Footer />
      </main>
    </>
  );
}