import React, { useEffect, useState } from "react";
import Head from "next/head";
import { Inter } from "next/font/google";
import Image from "next/image";
import Link from "next/link";
import { Navbar, Footer } from "./../../../components";
import { RiArrowGoBackLine } from "react-icons/ri";
import { useRouter } from "next/router";
import axios from "axios";

export default function ActivateCode() {
  const navigation = useRouter();
  const [isVerified, setIsVerified] = useState(false)
  const [userType, setUserType] = useState("");
  const [digit1, setDigit1] = useState('')
  const [digit2, setDigit2] = useState('')
  const [digit3, setDigit3] = useState('')
  const [digit4, setDigit4] = useState('')
  const [digit5, setDigit5] = useState('')
  const [digit6, setDigit6] = useState('')

  const isValid = digit1 && digit2 && digit3 && digit4 && digit5 && digit6

  const onContinue =async () => {
    try {
        const code = (digit1 + digit2 + digit3 + digit4 + digit5 + digit6);
        var stored = JSON.parse(window.localStorage.getItem("registrationForm"));
        console.log(code,stored)
        
        const response = await axios.post(`http://34.227.65.157/auth/code`, {
          email: stored.email,
          code: code
        });

        setIsVerified(true)
        console.log(response);
            if (userType === "parent") {
      navigation.push("/auth/registerparent");
    }
    if (userType === "instructor") {
      navigation.push("/auth/registerinstructor");
    }
    if (userType === "student") {
      navigation.push("/auth/registerstudent");
    }
     
      } catch (error) {
        console.error(error);
      }

  };

  useEffect(() => {
    const value = JSON.parse(window.localStorage.getItem("userType"));
    setUserType(value);
  }, []);

    return (
    <>
      <Head>
        <title>Auth | Activate Code</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container-fluid  d-flex flex-column justify-content-between  min-vh-100">
        <Link
          href="/"
          className="text-decoration-none p-4 d-flex gap-2 align-items-center text-dark"
        >
          <RiArrowGoBackLine />
          <p className="fw-bold m-0 p-0 ">Back to home</p>
        </Link>
        <div className="row">
          <div className="col-12 col-lg-6 d-flex justify-content-center align-items-center ">
            <div style={{ maxWidth: "380px", width: "100%" }}>
              {/* <h1 className="text-center mb-5">GSK</h1> */}
              <div className="d-flex justify-content-center mb-5">
                <Image
                  src="/assets/logo.png"
                  alt="Vercel Logo"
                  className=""
                  width={100}
                  height={50}
                  priority
                />
              </div>
              <div>
                <div className="d-flex justify-content-center mb-3">
                  <h5 className="text-secondary fw-bold text-center">
                    Check your email for activation code and enter it below
                  </h5>
                </div>
                
                <div className="d-flex gap-2">
                  <input
                    type="text"
                    maxLength="1"
                    className="w-full p-2 h3 rounded outline-0 border border_gray text_gray mb-3 text-center"
                    style={{ width: "100%" }}
                    placeholder=""
                    value={digit1}
                    onChange={(e)=> setDigit1(e.target.value)}
                  />
                  <input
                    type="text"
                    maxLength="1"
                    className="w-full p-2 h3 rounded outline-0 border border_gray text_gray mb-3 text-center"
                    style={{ width: "100%" }}
                    placeholder=""
                    value={digit2}
                    onChange={(e)=> setDigit2(e.target.value)}
                  />
                  <input
                    type="text"
                    maxLength="1"
                    className="w-full p-2 h3 rounded outline-0 border border_gray text_gray mb-3 text-center"
                    style={{ width: "100%" }}
                    placeholder=""
                    value={digit3}
                    onChange={(e)=> setDigit3(e.target.value)}
                  />
                  <input
                    type="text"
                    maxLength="1"
                    className="w-full p-2 h3 rounded outline-0 border border_gray text_gray mb-3 text-center"
                    style={{ width: "100%" }}
                    placeholder=""
                    value={digit4}
                    onChange={(e)=> setDigit4(e.target.value)}
                  />
                  <input
                    type="text"
                    maxLength="1"
                    className="w-full p-2 h3 rounded outline-0 border border_gray text_gray mb-3 text-center"
                    style={{ width: "100%" }}
                    placeholder=""
                    value={digit5}
                    onChange={(e)=> setDigit5(e.target.value)}
                  />
                  <input
                    type="text"
                    maxLength="1"
                    className="w-full p-2 h3 rounded outline-0 border border_gray text_gray mb-3 text-center"
                    style={{ width: "100%" }}
                    placeholder=""
                    value={digit6}
                    onChange={(e)=> setDigit6(e.target.value)}
                  />
                </div>
                <button
                 className={`w-100 text-light p-2 rounded fw-bold mt-3 bg-gray-300 ${!isValid ? 'btn_disabled' : 'btn_primary'}`}
                    disabled={!isValid}
                  onClick={onContinue}
                >
                  Continue
                </button>
                <div className="d-flex flex-column justify-content-center align-items-center mt-3">
                  <hr className="w-25" />
                  {
                    isVerified &&  <p className="fw-bold text_secondary m-0 p-0">
                    Activation code has been resent
                  </p>
                  }
                  <p className="text-secondary fw-bold m-0 p-0 pb-2">
                    Resend Activation Code
                  </p>

                  <button
                    className="w-50 btn_secondary text-light p-2 rounded fw-bold "
                    onClick={() => navigation.push("/auth/signin")}
                  >
                    Login
                  </button>
                </div>
              </div>
            </div>
          </div>
          <div
            className="col-12 col-lg-6 position-relative d-none d-md-block"
            style={{
              backgroundImage: 'url("/assets/auth_2.png")',
              height: "100vh",
              backgroundRepeat: "no-repeat",
              backgroundSize: "100% 100%",
            }}
          >
            <div style={{ position: "absolute", right: "0%", bottom: "7%" }}>
              <Image
                src="/assets/auth_girl_1.png"
                alt="Vercel Logo"
                className=""
                width={400}
                height={600}
                priority
              />
            </div>
          </div>
        </div>
        <Footer />
      </main>
    </>
  );
}
