import React, { useEffect, useState } from "react";
import Head from "next/head";
import { Inter } from "next/font/google";
import Image from "next/image";
import Link from "next/link";
import { Navbar, Footer } from "./../../../components";
import { RiArrowGoBackLine } from "react-icons/ri";
import { useRouter } from "next/router";

export default function ActivateCode() {
  const navigation = useRouter();
  const onContinue = () => {
    navigation.push("/auth/register");
  };
    return (
    <>
      <Head>
        <title>Auth | Activate Code</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container-fluid  d-flex flex-column justify-content-between  min-vh-100">
        <Link
          href="/"
          className="text-decoration-none p-4 d-flex gap-2 align-items-center text-dark"
        >
          <RiArrowGoBackLine />
          <p className="fw-bold m-0 p-0 ">Back to home</p>
        </Link>
        <div className="row">
          <div className="col-12 col-lg-6 d-flex justify-content-center align-items-center ">
            <div style={{ maxWidth: "380px", width: "100%" }}>
              {/* <h1 className="text-center mb-5">GSK</h1> */}
              <div className="d-flex justify-content-center mb-5">
                <Image
                  src="/assets/logo.png"
                  alt="Vercel Logo"
                  className=""
                  width={100}
                  height={50}
                  priority
                />
              </div>
              <div>
                <div className="d-flex justify-content-center mb-3">
                  <h5 className="text-secondary fw-bold text-center">
                    Check your email for activation code and enter it below
                  </h5>
                </div>
                <div className="d-flex gap-2">
                  <input
                    type="text"
                    maxLength="1"
                    className="w-full p-2 h3 rounded outline-0 border border_gray text_gray mb-3 text-center"
                    style={{ width: "100%" }}
                    placeholder=""
                  />
                  <input
                    type="text"
                    maxLength="1"
                    className="w-full p-2 h3 rounded outline-0 border border_gray text_gray mb-3 text-center"
                    style={{ width: "100%" }}
                    placeholder=""
                  />
                  <input
                    type="text"
                    maxLength="1"
                    className="w-full p-2 h3 rounded outline-0 border border_gray text_gray mb-3 text-center"
                    style={{ width: "100%" }}
                    placeholder=""
                  />
                  <input
                    type="text"
                    maxLength="1"
                    className="w-full p-2 h3 rounded outline-0 border border_gray text_gray mb-3 text-center"
                    style={{ width: "100%" }}
                    placeholder=""
                  />
                  <input
                    type="text"
                    maxLength="1"
                    className="w-full p-2 h3 rounded outline-0 border border_gray text_gray mb-3 text-center"
                    style={{ width: "100%" }}
                    placeholder=""
                  />
                  <input
                    type="text"
                    maxLength="1"
                    className="w-full p-2 h3 rounded outline-0 border border_gray text_gray mb-3 text-center"
                    style={{ width: "100%" }}
                    placeholder=""
                  />
                </div>
                <button
                  className="w-100 btn_primary text-light p-2 rounded fw-bold mt-3"
                  onClick={onContinue}
                >
                  Continue
                </button>
                <div className="d-flex flex-column justify-content-center align-items-center mt-3">
                  <hr className="w-25" />
                  <p className="fw-bold text_secondary m-0 p-0">
                    Activation code has been resent
                  </p>
                  <p className="text-secondary fw-bold m-0 p-0 pb-2">
                    Resend Activation Code
                  </p>

                  <button
                    className="w-50 btn_secondary text-light p-2 rounded fw-bold "
                    onClick={() => navigation.push("/auth/signin")}
                  >
                    Login
                  </button>
                </div>
              </div>
            </div>
          </div>
          <div
            className="col-12 col-lg-6 position-relative d-none d-md-block"
            style={{
              backgroundImage: 'url("/assets/auth_2.png")',
              height: "100vh",
              backgroundRepeat: "no-repeat",
              backgroundSize: "100% 100%",
            }}
          >
            <div style={{ position: "absolute", right: "0%", bottom: "7%" }}>
              <Image
                src="/assets/auth_girl_1.png"
                alt="Vercel Logo"
                className=""
                width={400}
                height={600}
                priority
              />
            </div>
          </div>
        </div>
        <Footer />
      </main>
    </>
  );
}
