import React, { useState,useEffect } from "react";
import Head from "next/head";
import { TutorNavbar, Footer } from "../../../components";
import {useRouter} from "next/router"
import { RiArrowGoBackLine } from "react-icons/ri";
import Link from "next/link";
import axios from 'axios'
export default function ParentRegistrationCCInfo() {
    const navigation = useRouter();
    const [userType, setUserType] = useState(null);
    const [userInfo, setUserInfo] = useState(null);

    const [bankAccountType, setBankAccountType] = useState('checking')
    const [bankName, setBankName] = useState('')
    const [bankAccountNumber, setBankAccountNumber] = useState('')
    const [bankRoutingNumber, setBankRoutingNumber] = useState('')
    const [confirmBankRoutingNumber, setConfirmBankRoutingNumber] = useState('')

    const onContinue = async () => {
        try {
            console.log(
                {
                        firstName: userInfo.firstName,
                lastName: userInfo.lastName,
                email: userInfo.email,
                password: userInfo.password,
                address1: userInfo.address1,
                address2: userInfo.address2,
                country: userInfo.country,
                state: userInfo.state,
                city: userInfo.city,
                zipCode: userInfo.zipCode,
                timeZoneId: 'Asia/Karachi',
                acceptInterviewRequest: true,
                gradesIdToTutor: userInfo.gradesIdToTutor,
                instructorBio: userInfo.instructorBio,
                hourlyRate: userInfo.hourlyRate,

                coursesIdToTutor: userInfo.coursesIdToTutor,
                proficienciesIdOfStudentsToTeach: userInfo.proficienciesIdOfStudentsToTeach,
                languagesIdPreference: userInfo.languagesIdPreference,
                bankAccountType: bankAccountType,
                bankAccountNumber:bankAccountNumber,
                bankRoutingNumber: bankRoutingNumber,
                bankName: bankName,
                }
            )
            const response = await axios.post(
              `http://34.227.65.157/auth/register-instructor`,
              {
                firstName: userInfo.firstName,
                lastName: userInfo.lastName,
                email: userInfo.email,
                password: userInfo.password,
                address1: userInfo.address1,
                address2: userInfo.address2,
                country: userInfo.country,
                state: userInfo.state,
                city: userInfo.city,
                zipCode: userInfo.zipCode,
                timeZoneId: 'Asia/Karachi',
                acceptInterviewRequest: true,
                instructorBio: userInfo.instructorBio,
                hourlyRate: userInfo.hourlyRate,

                gradesIdToTutor: userInfo.gradesIdToTutor,
                coursesIdToTutor: userInfo.coursesIdToTutor,
                proficienciesIdOfStudentsToTeach: userInfo.proficienciesIdOfStudentsToTeach,
                languagesIdPreference: userInfo.languagesIdPreference,
                bankAccountType: bankAccountType,
                bankAccountNumber:bankAccountNumber,
                bankRoutingNumber: bankRoutingNumber,
                bankName: bankName,
              }
            );
            window.localStorage.setItem("gkcAuth", JSON.stringify(response.data))
            window.localStorage.removeItem("registrationForm")
            window.localStorage.removeItem("userType")
            console.log(response.data)
            navigation.push("/instructor");

    
          } catch (error) {
            console.error(error);
          }
      };


      useEffect(() => {
        var stored = JSON.parse(window.localStorage.getItem("registrationForm"));
        var typ = JSON.parse(window.localStorage.getItem("userType"));
        setUserInfo(stored);
        setUserType(typ);
      }, []);
  return (
    <>
      <Head>
        <title>Auth | Instructor CC Info</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container-fluid">
      <Link
          href="/"
          className="text-decoration-none p-4 d-flex gap-2 align-items-center text-dark"
        >
          <RiArrowGoBackLine />
          <p className="fw-bold m-0 p-0 ">Back to home</p>
        </Link>
        <div className="row">
          <div
            className="col-12 col-lg-5 position-relative"
            style={{
              backgroundImage: 'url("/assets/register_group.png")',
              height: "100vh",
              backgroundRepeat: "no-repeat",
              backgroundSize: "100% 100%",
            }}
          ></div>
          <div className="col-12 col-lg-7 d-flex justify-content-center align-items-center ">
            <div className="w-75 p-5">
              <div>
                        <h4 className="text-dark fw-bold pb-2">
                 Tell us where to deposit your payments.
                </h4>
                <select className="w-100 p-2 rounded outline-0 border border_gray text_gray mb-3 " value={bankAccountType} onChange={(e)=>setBankAccountType(e.target.value)}>
                    <option value='checking'>Checking</option>
                    <option value='saving'>Saving</option>
                  </select>
                <input
                  type="text"
                  className="w-100 p-2 rounded outline-0 border border_gray text_gray  my-2"
                  placeholder="Bank Name"
                  value={bankName} onChange={(e)=>setBankName(e.target.value)}
                />
                <input
                  type="text"
                  className="w-100 p-2 rounded outline-0 border border_gray text_gray  my-2"
                  placeholder="Account Number"
                  value={bankAccountNumber} onChange={(e)=>setBankAccountNumber(e.target.value)}

                />

                <div className="d-flex gap-2 my-2">
                  <input
                    type="text"
                    className="w-100 p-2 rounded outline-0 border border_gray text_gray  mb-3"
                    placeholder="Routing Number"
                  value={bankRoutingNumber} onChange={(e)=>setBankRoutingNumber(e.target.value)}

                  />
                  <input
                    type="text"
                    className="w-100 p-2 rounded outline-0 border border_gray text_gray  mb-3"
                    placeholder="Confrim Routing Number"
                  value={confirmBankRoutingNumber} onChange={(e)=>setConfirmBankRoutingNumber(e.target.value)}

                  />
                </div>
                <div className="d-flex gap-2 justify-content-center mt-3">
                  <button
                       className={`w-50 text-light p-2 rounded fw-bold  bg-gray-300 ${
                        bankRoutingNumber === ''  ? "btn_disabled" : "btn_primary"
                      }`}
                      disabled={  bankRoutingNumber === ''}
                      onClick={onContinue}
                  >
                    Continue
                  </button>
                </div>
                <div className="d-flex gap-2 justify-content-center  mt-3">
                  <button
                    className={`w-50 text-light p-2 rounded fw-bold  bg-gray-300 ${
                        bankRoutingNumber === ''? "btn_disabled" : "btn_secondary"
                      }`}
                      disabled={ bankRoutingNumber === ''}
                    onClick={onContinue}
                  >
                    I wil do this later
                  </button>
                </div>
           
              </div>
            </div>
          </div>
        </div>

        <Footer />
      </main>
    </>
  );
}
