import ContactUs from '@/components/contactUs';
import Head from 'next/head';
import { withRole } from '@/utils/withAuthorization';
import Navbar from '@/components/navbar_2/navbar';

function StudentContactUs() {
  return (
    <>
      <Head>
        <title>Auth | CC Info</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar isLogin={true} />
      <ContactUs />
    </>
  );
}

export default withRole(StudentContactUs, ['Student']);
